// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransfer = `-- name: GetTransfer :one
SELECT transfer_id, tenant_id, operation_id, attempt_id, class, media_type, expected_digest, expected_size, handle, state, object_version, reason_code, command_id, request_digest, deadline, created_at, finalized_at, actor_id, execution_epoch, recovery_epoch, object_key, actual_size, actual_digest, finalize_command_id, finalize_request_digest, updated_at FROM artifact_transfers WHERE transfer_id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, transferID string) (ArtifactTransfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, transferID)
	var i ArtifactTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.Class,
		&i.MediaType,
		&i.ExpectedDigest,
		&i.ExpectedSize,
		&i.Handle,
		&i.State,
		&i.ObjectVersion,
		&i.ReasonCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ActorID,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.ObjectKey,
		&i.ActualSize,
		&i.ActualDigest,
		&i.FinalizeCommandID,
		&i.FinalizeRequestDigest,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransferByCommand = `-- name: GetTransferByCommand :one

SELECT transfer_id, tenant_id, operation_id, attempt_id, class, media_type, expected_digest, expected_size, handle, state, object_version, reason_code, command_id, request_digest, deadline, created_at, finalized_at, actor_id, execution_epoch, recovery_epoch, object_key, actual_size, actual_digest, finalize_command_id, finalize_request_digest, updated_at FROM artifact_transfers WHERE tenant_id = $1 AND command_id = $2
`

type GetTransferByCommandParams struct {
	TenantID  string
	CommandID string
}

// Scoped artifact transfers (DD-02 §6, P08). Lock ranks: operation (2),
// attempt/instance (3), transfer (6, an accepted-result record). The
// application reads the object outside every lock and revalidates under the
// transfer lock before finalizing. object_key is Control's own locator and
// never leaves the adapter or the application layer.
func (q *Queries) GetTransferByCommand(ctx context.Context, arg GetTransferByCommandParams) (ArtifactTransfer, error) {
	row := q.db.QueryRow(ctx, getTransferByCommand, arg.TenantID, arg.CommandID)
	var i ArtifactTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.Class,
		&i.MediaType,
		&i.ExpectedDigest,
		&i.ExpectedSize,
		&i.Handle,
		&i.State,
		&i.ObjectVersion,
		&i.ReasonCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ActorID,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.ObjectKey,
		&i.ActualSize,
		&i.ActualDigest,
		&i.FinalizeCommandID,
		&i.FinalizeRequestDigest,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransferByHandle = `-- name: GetTransferByHandle :one
SELECT transfer_id, tenant_id, operation_id, attempt_id, class, media_type, expected_digest, expected_size, handle, state, object_version, reason_code, command_id, request_digest, deadline, created_at, finalized_at, actor_id, execution_epoch, recovery_epoch, object_key, actual_size, actual_digest, finalize_command_id, finalize_request_digest, updated_at FROM artifact_transfers WHERE handle = $1
`

func (q *Queries) GetTransferByHandle(ctx context.Context, handle string) (ArtifactTransfer, error) {
	row := q.db.QueryRow(ctx, getTransferByHandle, handle)
	var i ArtifactTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.Class,
		&i.MediaType,
		&i.ExpectedDigest,
		&i.ExpectedSize,
		&i.Handle,
		&i.State,
		&i.ObjectVersion,
		&i.ReasonCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ActorID,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.ObjectKey,
		&i.ActualSize,
		&i.ActualDigest,
		&i.FinalizeCommandID,
		&i.FinalizeRequestDigest,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStageArtifact = `-- name: InsertStageArtifact :exec
INSERT INTO stage_artifacts (stage_id, transfer_id, handle, class, digest, size_bytes, object_version) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertStageArtifactParams struct {
	StageID       string
	TransferID    string
	Handle        string
	Class         string
	Digest        string
	SizeBytes     int64
	ObjectVersion string
}

func (q *Queries) InsertStageArtifact(ctx context.Context, arg InsertStageArtifactParams) error {
	_, err := q.db.Exec(ctx, insertStageArtifact,
		arg.StageID,
		arg.TransferID,
		arg.Handle,
		arg.Class,
		arg.Digest,
		arg.SizeBytes,
		arg.ObjectVersion,
	)
	return err
}

const insertTransfer = `-- name: InsertTransfer :exec
INSERT INTO artifact_transfers (
    transfer_id, tenant_id, operation_id, attempt_id, class, media_type, expected_digest, expected_size, handle, state,
    object_version, reason_code, command_id, request_digest, deadline, created_at, finalized_at,
    actor_id, execution_epoch, recovery_epoch, object_key, actual_size, actual_digest, finalize_command_id, finalize_request_digest, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25, $26
)
`

type InsertTransferParams struct {
	TransferID            string
	TenantID              string
	OperationID           *string
	AttemptID             *string
	Class                 string
	MediaType             string
	ExpectedDigest        string
	ExpectedSize          int64
	Handle                string
	State                 string
	ObjectVersion         *string
	ReasonCode            *string
	CommandID             string
	RequestDigest         string
	Deadline              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	FinalizedAt           pgtype.Timestamptz
	ActorID               string
	ExecutionEpoch        int64
	RecoveryEpoch         int64
	ObjectKey             string
	ActualSize            *int64
	ActualDigest          *string
	FinalizeCommandID     *string
	FinalizeRequestDigest *string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) error {
	_, err := q.db.Exec(ctx, insertTransfer,
		arg.TransferID,
		arg.TenantID,
		arg.OperationID,
		arg.AttemptID,
		arg.Class,
		arg.MediaType,
		arg.ExpectedDigest,
		arg.ExpectedSize,
		arg.Handle,
		arg.State,
		arg.ObjectVersion,
		arg.ReasonCode,
		arg.CommandID,
		arg.RequestDigest,
		arg.Deadline,
		arg.CreatedAt,
		arg.FinalizedAt,
		arg.ActorID,
		arg.ExecutionEpoch,
		arg.RecoveryEpoch,
		arg.ObjectKey,
		arg.ActualSize,
		arg.ActualDigest,
		arg.FinalizeCommandID,
		arg.FinalizeRequestDigest,
		arg.UpdatedAt,
	)
	return err
}

const listStageArtifacts = `-- name: ListStageArtifacts :many
SELECT stage_id, transfer_id, handle, class, digest, size_bytes, object_version FROM stage_artifacts WHERE stage_id = $1 ORDER BY handle
`

func (q *Queries) ListStageArtifacts(ctx context.Context, stageID string) ([]StageArtifact, error) {
	rows, err := q.db.Query(ctx, listStageArtifacts, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageArtifact{}
	for rows.Next() {
		var i StageArtifact
		if err := rows.Scan(
			&i.StageID,
			&i.TransferID,
			&i.Handle,
			&i.Class,
			&i.Digest,
			&i.SizeBytes,
			&i.ObjectVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTransfer = `-- name: LockTransfer :one
SELECT transfer_id, tenant_id, operation_id, attempt_id, class, media_type, expected_digest, expected_size, handle, state, object_version, reason_code, command_id, request_digest, deadline, created_at, finalized_at, actor_id, execution_epoch, recovery_epoch, object_key, actual_size, actual_digest, finalize_command_id, finalize_request_digest, updated_at FROM artifact_transfers WHERE transfer_id = $1 FOR UPDATE
`

func (q *Queries) LockTransfer(ctx context.Context, transferID string) (ArtifactTransfer, error) {
	row := q.db.QueryRow(ctx, lockTransfer, transferID)
	var i ArtifactTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.Class,
		&i.MediaType,
		&i.ExpectedDigest,
		&i.ExpectedSize,
		&i.Handle,
		&i.State,
		&i.ObjectVersion,
		&i.ReasonCode,
		&i.CommandID,
		&i.RequestDigest,
		&i.Deadline,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.ActorID,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.ObjectKey,
		&i.ActualSize,
		&i.ActualDigest,
		&i.FinalizeCommandID,
		&i.FinalizeRequestDigest,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransfer = `-- name: UpdateTransfer :exec
UPDATE artifact_transfers SET state = $2, object_version = $3, reason_code = $4, finalized_at = $5, actual_size = $6, actual_digest = $7,
    finalize_command_id = $8, finalize_request_digest = $9, updated_at = $10
WHERE transfer_id = $1
`

type UpdateTransferParams struct {
	TransferID            string
	State                 string
	ObjectVersion         *string
	ReasonCode            *string
	FinalizedAt           pgtype.Timestamptz
	ActualSize            *int64
	ActualDigest          *string
	FinalizeCommandID     *string
	FinalizeRequestDigest *string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error {
	_, err := q.db.Exec(ctx, updateTransfer,
		arg.TransferID,
		arg.State,
		arg.ObjectVersion,
		arg.ReasonCode,
		arg.FinalizedAt,
		arg.ActualSize,
		arg.ActualDigest,
		arg.FinalizeCommandID,
		arg.FinalizeRequestDigest,
		arg.UpdatedAt,
	)
	return err
}
