// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dispatch.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chargedCost = `-- name: ChargedCost :one
SELECT coalesce(sum(amount), 0)::bigint AS amount, coalesce(min(entry_id) FILTER (WHERE kind = 'actual'), '')::text AS actual_entry_id
FROM cost_entries WHERE dispatch_id = $1 AND kind IN ('actual', 'correction')
`

type ChargedCostRow struct {
	Amount        int64
	ActualEntryID string
}

func (q *Queries) ChargedCost(ctx context.Context, dispatchID *string) (ChargedCostRow, error) {
	row := q.db.QueryRow(ctx, chargedCost, dispatchID)
	var i ChargedCostRow
	err := row.Scan(&i.Amount, &i.ActualEntryID)
	return i, err
}

const findDispatchesByOwnerCall = `-- name: FindDispatchesByOwnerCall :many
SELECT dispatch_id, kind, tenant_id, operation_id, attempt_id, instance_id, call_id, owner, request_digest, route_id, grant_id, grant_revision, execution_epoch, state, outcome, reserved_currency, reserved_amount, meter_revision, supersedes_call_id, evidence_ref, inventory_state, inventory_version, deadline, admitted_at, observed_at, denial_code FROM dispatches WHERE owner = $1 AND call_id = $2 ORDER BY admitted_at LIMIT 2
`

type FindDispatchesByOwnerCallParams struct {
	Owner  string
	CallID string
}

func (q *Queries) FindDispatchesByOwnerCall(ctx context.Context, arg FindDispatchesByOwnerCallParams) ([]Dispatch, error) {
	rows, err := q.db.Query(ctx, findDispatchesByOwnerCall, arg.Owner, arg.CallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dispatch{}
	for rows.Next() {
		var i Dispatch
		if err := rows.Scan(
			&i.DispatchID,
			&i.Kind,
			&i.TenantID,
			&i.OperationID,
			&i.AttemptID,
			&i.InstanceID,
			&i.CallID,
			&i.Owner,
			&i.RequestDigest,
			&i.RouteID,
			&i.GrantID,
			&i.GrantRevision,
			&i.ExecutionEpoch,
			&i.State,
			&i.Outcome,
			&i.ReservedCurrency,
			&i.ReservedAmount,
			&i.MeterRevision,
			&i.SupersedesCallID,
			&i.EvidenceRef,
			&i.InventoryState,
			&i.InventoryVersion,
			&i.Deadline,
			&i.AdmittedAt,
			&i.ObservedAt,
			&i.DenialCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllocationByPool = `-- name: GetAllocationByPool :one
SELECT allocation_id, pool_id, operation_id, currency, amount, reserved, consumed, revision, created_at FROM allocations WHERE pool_id = $1 AND operation_id = $2
`

type GetAllocationByPoolParams struct {
	PoolID      string
	OperationID string
}

func (q *Queries) GetAllocationByPool(ctx context.Context, arg GetAllocationByPoolParams) (Allocation, error) {
	row := q.db.QueryRow(ctx, getAllocationByPool, arg.PoolID, arg.OperationID)
	var i Allocation
	err := row.Scan(
		&i.AllocationID,
		&i.PoolID,
		&i.OperationID,
		&i.Currency,
		&i.Amount,
		&i.Reserved,
		&i.Consumed,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const getDispatch = `-- name: GetDispatch :one
SELECT dispatch_id, kind, tenant_id, operation_id, attempt_id, instance_id, call_id, owner, request_digest, route_id, grant_id, grant_revision, execution_epoch, state, outcome, reserved_currency, reserved_amount, meter_revision, supersedes_call_id, evidence_ref, inventory_state, inventory_version, deadline, admitted_at, observed_at, denial_code FROM dispatches WHERE dispatch_id = $1
`

func (q *Queries) GetDispatch(ctx context.Context, dispatchID string) (Dispatch, error) {
	row := q.db.QueryRow(ctx, getDispatch, dispatchID)
	var i Dispatch
	err := row.Scan(
		&i.DispatchID,
		&i.Kind,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.InstanceID,
		&i.CallID,
		&i.Owner,
		&i.RequestDigest,
		&i.RouteID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ExecutionEpoch,
		&i.State,
		&i.Outcome,
		&i.ReservedCurrency,
		&i.ReservedAmount,
		&i.MeterRevision,
		&i.SupersedesCallID,
		&i.EvidenceRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.Deadline,
		&i.AdmittedAt,
		&i.ObservedAt,
		&i.DenialCode,
	)
	return i, err
}

const getDispatchByCall = `-- name: GetDispatchByCall :one
SELECT dispatch_id, kind, tenant_id, operation_id, attempt_id, instance_id, call_id, owner, request_digest, route_id, grant_id, grant_revision, execution_epoch, state, outcome, reserved_currency, reserved_amount, meter_revision, supersedes_call_id, evidence_ref, inventory_state, inventory_version, deadline, admitted_at, observed_at, denial_code FROM dispatches WHERE tenant_id = $1 AND owner = $2 AND call_id = $3
`

type GetDispatchByCallParams struct {
	TenantID string
	Owner    string
	CallID   string
}

func (q *Queries) GetDispatchByCall(ctx context.Context, arg GetDispatchByCallParams) (Dispatch, error) {
	row := q.db.QueryRow(ctx, getDispatchByCall, arg.TenantID, arg.Owner, arg.CallID)
	var i Dispatch
	err := row.Scan(
		&i.DispatchID,
		&i.Kind,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.InstanceID,
		&i.CallID,
		&i.Owner,
		&i.RequestDigest,
		&i.RouteID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ExecutionEpoch,
		&i.State,
		&i.Outcome,
		&i.ReservedCurrency,
		&i.ReservedAmount,
		&i.MeterRevision,
		&i.SupersedesCallID,
		&i.EvidenceRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.Deadline,
		&i.AdmittedAt,
		&i.ObservedAt,
		&i.DenialCode,
	)
	return i, err
}

const getGrantPolicy = `-- name: GetGrantPolicy :one
SELECT grant_id, grant_revision, tenant_id, policy_digest, server_id, methods, cost_cap_currency, cost_cap_amount, expires_at, policy_epoch, receipt_id, revocation_state, fenced_at, converged_at, registered_at FROM grant_policies WHERE grant_id = $1 AND grant_revision = $2
`

type GetGrantPolicyParams struct {
	GrantID       string
	GrantRevision int64
}

func (q *Queries) GetGrantPolicy(ctx context.Context, arg GetGrantPolicyParams) (GrantPolicy, error) {
	row := q.db.QueryRow(ctx, getGrantPolicy, arg.GrantID, arg.GrantRevision)
	var i GrantPolicy
	err := row.Scan(
		&i.GrantID,
		&i.GrantRevision,
		&i.TenantID,
		&i.PolicyDigest,
		&i.ServerID,
		&i.Methods,
		&i.CostCapCurrency,
		&i.CostCapAmount,
		&i.ExpiresAt,
		&i.PolicyEpoch,
		&i.ReceiptID,
		&i.RevocationState,
		&i.FencedAt,
		&i.ConvergedAt,
		&i.RegisteredAt,
	)
	return i, err
}

const getUsageObservation = `-- name: GetUsageObservation :one
SELECT observation_id, dispatch_id, source, sequence, native_reference, input_units, output_units, reasoning_units, cached_input_units, cost_revision, observed_at, usage_reported FROM usage_observations WHERE dispatch_id = $1 AND source = $2 AND sequence = $3
`

type GetUsageObservationParams struct {
	DispatchID string
	Source     string
	Sequence   int64
}

func (q *Queries) GetUsageObservation(ctx context.Context, arg GetUsageObservationParams) (UsageObservation, error) {
	row := q.db.QueryRow(ctx, getUsageObservation, arg.DispatchID, arg.Source, arg.Sequence)
	var i UsageObservation
	err := row.Scan(
		&i.ObservationID,
		&i.DispatchID,
		&i.Source,
		&i.Sequence,
		&i.NativeReference,
		&i.InputUnits,
		&i.OutputUnits,
		&i.ReasoningUnits,
		&i.CachedInputUnits,
		&i.CostRevision,
		&i.ObservedAt,
		&i.UsageReported,
	)
	return i, err
}

const hasOverspend = `-- name: HasOverspend :one
SELECT EXISTS (
    SELECT 1 FROM dispatches d
    WHERE d.operation_id = $1 AND d.state IN ('authorized', 'observed', 'unknown')
      AND (SELECT coalesce(sum(c.amount), 0) FROM cost_entries c WHERE c.dispatch_id = d.dispatch_id AND c.kind IN ('actual', 'correction')) > d.reserved_amount
)
`

func (q *Queries) HasOverspend(ctx context.Context, operationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOverspend, operationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasReportedUsage = `-- name: HasReportedUsage :one
SELECT EXISTS (SELECT 1 FROM usage_observations WHERE dispatch_id = $1 AND usage_reported)
`

func (q *Queries) HasReportedUsage(ctx context.Context, dispatchID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasReportedUsage, dispatchID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasUnknownDispatch = `-- name: HasUnknownDispatch :one
SELECT EXISTS (SELECT 1 FROM dispatches WHERE operation_id = $1 AND state = 'unknown')
`

func (q *Queries) HasUnknownDispatch(ctx context.Context, operationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnknownDispatch, operationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO allocations (allocation_id, pool_id, operation_id, currency, amount, reserved, consumed, revision, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAllocationParams struct {
	AllocationID string
	PoolID       string
	OperationID  string
	Currency     string
	Amount       int64
	Reserved     int64
	Consumed     int64
	Revision     int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.Exec(ctx, insertAllocation,
		arg.AllocationID,
		arg.PoolID,
		arg.OperationID,
		arg.Currency,
		arg.Amount,
		arg.Reserved,
		arg.Consumed,
		arg.Revision,
		arg.CreatedAt,
	)
	return err
}

const insertCostEntry = `-- name: InsertCostEntry :exec
INSERT INTO cost_entries (entry_id, operation_id, dispatch_id, observation_id, kind, currency, amount, correction_of, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertCostEntryParams struct {
	EntryID       string
	OperationID   string
	DispatchID    *string
	ObservationID *string
	Kind          string
	Currency      string
	Amount        int64
	CorrectionOf  *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertCostEntry(ctx context.Context, arg InsertCostEntryParams) error {
	_, err := q.db.Exec(ctx, insertCostEntry,
		arg.EntryID,
		arg.OperationID,
		arg.DispatchID,
		arg.ObservationID,
		arg.Kind,
		arg.Currency,
		arg.Amount,
		arg.CorrectionOf,
		arg.CreatedAt,
	)
	return err
}

const insertDispatch = `-- name: InsertDispatch :exec
INSERT INTO dispatches (
    dispatch_id, kind, tenant_id, operation_id, attempt_id, instance_id, call_id, owner, request_digest, route_id,
    grant_id, grant_revision, execution_epoch, state, outcome, denial_code, reserved_currency, reserved_amount, meter_revision,
    supersedes_call_id, evidence_ref, inventory_state, inventory_version, deadline, admitted_at, observed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26
)
`

type InsertDispatchParams struct {
	DispatchID       string
	Kind             string
	TenantID         string
	OperationID      string
	AttemptID        string
	InstanceID       *string
	CallID           string
	Owner            string
	RequestDigest    string
	RouteID          *string
	GrantID          *string
	GrantRevision    *int64
	ExecutionEpoch   int64
	State            string
	Outcome          *string
	DenialCode       *string
	ReservedCurrency string
	ReservedAmount   int64
	MeterRevision    string
	SupersedesCallID *string
	EvidenceRef      *string
	InventoryState   string
	InventoryVersion *string
	Deadline         pgtype.Timestamptz
	AdmittedAt       pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
}

func (q *Queries) InsertDispatch(ctx context.Context, arg InsertDispatchParams) error {
	_, err := q.db.Exec(ctx, insertDispatch,
		arg.DispatchID,
		arg.Kind,
		arg.TenantID,
		arg.OperationID,
		arg.AttemptID,
		arg.InstanceID,
		arg.CallID,
		arg.Owner,
		arg.RequestDigest,
		arg.RouteID,
		arg.GrantID,
		arg.GrantRevision,
		arg.ExecutionEpoch,
		arg.State,
		arg.Outcome,
		arg.DenialCode,
		arg.ReservedCurrency,
		arg.ReservedAmount,
		arg.MeterRevision,
		arg.SupersedesCallID,
		arg.EvidenceRef,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.Deadline,
		arg.AdmittedAt,
		arg.ObservedAt,
	)
	return err
}

const insertUsageObservation = `-- name: InsertUsageObservation :exec
INSERT INTO usage_observations (observation_id, dispatch_id, source, sequence, native_reference, input_units, output_units, reasoning_units, cached_input_units, cost_revision, observed_at, usage_reported)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertUsageObservationParams struct {
	ObservationID    string
	DispatchID       string
	Source           string
	Sequence         int64
	NativeReference  string
	InputUnits       int64
	OutputUnits      int64
	ReasoningUnits   int64
	CachedInputUnits int64
	CostRevision     string
	ObservedAt       pgtype.Timestamptz
	UsageReported    bool
}

func (q *Queries) InsertUsageObservation(ctx context.Context, arg InsertUsageObservationParams) error {
	_, err := q.db.Exec(ctx, insertUsageObservation,
		arg.ObservationID,
		arg.DispatchID,
		arg.Source,
		arg.Sequence,
		arg.NativeReference,
		arg.InputUnits,
		arg.OutputUnits,
		arg.ReasoningUnits,
		arg.CachedInputUnits,
		arg.CostRevision,
		arg.ObservedAt,
		arg.UsageReported,
	)
	return err
}

const listCurrentPools = `-- name: ListCurrentPools :many

SELECT pool_id, level, tenant_id, actor_id, period_start, period_end, currency, cap_amount, allocated, revision FROM budget_pools
WHERE currency = $1 AND period_start <= $2 AND period_end > $2
  AND ((level = 'platform' AND tenant_id IS NULL AND actor_id IS NULL)
    OR (level = 'tenant' AND tenant_id = $3 AND actor_id IS NULL)
    OR (level = 'actor' AND tenant_id = $3 AND actor_id = $4))
ORDER BY pool_id
`

type ListCurrentPoolsParams struct {
	Currency    string
	PeriodStart pgtype.Timestamptz
	TenantID    *string
	ActorID     *string
}

// Budgets, single-use dispatch admission, metering and the grant-policy
// projection (DD-02 §3–§4, delivery.md P06). Lock ranks: pools and
// allocations (1) before the operation (2), attempt/instance (3), the
// dispatch (4) and the ledger (6); the application acquires them in that
// order and never performs I/O while any is held.
func (q *Queries) ListCurrentPools(ctx context.Context, arg ListCurrentPoolsParams) ([]BudgetPool, error) {
	rows, err := q.db.Query(ctx, listCurrentPools,
		arg.Currency,
		arg.PeriodStart,
		arg.TenantID,
		arg.ActorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetPool{}
	for rows.Next() {
		var i BudgetPool
		if err := rows.Scan(
			&i.PoolID,
			&i.Level,
			&i.TenantID,
			&i.ActorID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Currency,
			&i.CapAmount,
			&i.Allocated,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAllocations = `-- name: LockAllocations :many
SELECT allocation_id, pool_id, operation_id, currency, amount, reserved, consumed, revision, created_at FROM allocations WHERE operation_id = $1 ORDER BY pool_id FOR UPDATE
`

func (q *Queries) LockAllocations(ctx context.Context, operationID string) ([]Allocation, error) {
	rows, err := q.db.Query(ctx, lockAllocations, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Allocation{}
	for rows.Next() {
		var i Allocation
		if err := rows.Scan(
			&i.AllocationID,
			&i.PoolID,
			&i.OperationID,
			&i.Currency,
			&i.Amount,
			&i.Reserved,
			&i.Consumed,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDispatch = `-- name: LockDispatch :one
SELECT dispatch_id, kind, tenant_id, operation_id, attempt_id, instance_id, call_id, owner, request_digest, route_id, grant_id, grant_revision, execution_epoch, state, outcome, reserved_currency, reserved_amount, meter_revision, supersedes_call_id, evidence_ref, inventory_state, inventory_version, deadline, admitted_at, observed_at, denial_code FROM dispatches WHERE dispatch_id = $1 FOR UPDATE
`

func (q *Queries) LockDispatch(ctx context.Context, dispatchID string) (Dispatch, error) {
	row := q.db.QueryRow(ctx, lockDispatch, dispatchID)
	var i Dispatch
	err := row.Scan(
		&i.DispatchID,
		&i.Kind,
		&i.TenantID,
		&i.OperationID,
		&i.AttemptID,
		&i.InstanceID,
		&i.CallID,
		&i.Owner,
		&i.RequestDigest,
		&i.RouteID,
		&i.GrantID,
		&i.GrantRevision,
		&i.ExecutionEpoch,
		&i.State,
		&i.Outcome,
		&i.ReservedCurrency,
		&i.ReservedAmount,
		&i.MeterRevision,
		&i.SupersedesCallID,
		&i.EvidenceRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.Deadline,
		&i.AdmittedAt,
		&i.ObservedAt,
		&i.DenialCode,
	)
	return i, err
}

const lockPool = `-- name: LockPool :one
SELECT pool_id, level, tenant_id, actor_id, period_start, period_end, currency, cap_amount, allocated, revision FROM budget_pools WHERE pool_id = $1 FOR UPDATE
`

func (q *Queries) LockPool(ctx context.Context, poolID string) (BudgetPool, error) {
	row := q.db.QueryRow(ctx, lockPool, poolID)
	var i BudgetPool
	err := row.Scan(
		&i.PoolID,
		&i.Level,
		&i.TenantID,
		&i.ActorID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.CapAmount,
		&i.Allocated,
		&i.Revision,
	)
	return i, err
}

const maxUsage = `-- name: MaxUsage :one
SELECT coalesce(max(input_units), 0)::bigint AS input_units, coalesce(max(output_units), 0)::bigint AS output_units,
       coalesce(max(reasoning_units), 0)::bigint AS reasoning_units, coalesce(max(cached_input_units), 0)::bigint AS cached_input_units
FROM usage_observations WHERE dispatch_id = $1 AND usage_reported
`

type MaxUsageRow struct {
	InputUnits       int64
	OutputUnits      int64
	ReasoningUnits   int64
	CachedInputUnits int64
}

// MaxUsage is the running maximum of the explicitly reported counters; a
// report without usage (usage_reported = false) never enters it.
func (q *Queries) MaxUsage(ctx context.Context, dispatchID string) (MaxUsageRow, error) {
	row := q.db.QueryRow(ctx, maxUsage, dispatchID)
	var i MaxUsageRow
	err := row.Scan(
		&i.InputUnits,
		&i.OutputUnits,
		&i.ReasoningUnits,
		&i.CachedInputUnits,
	)
	return i, err
}

const updateAllocation = `-- name: UpdateAllocation :exec
UPDATE allocations SET reserved = $2, consumed = $3, revision = $4 WHERE allocation_id = $1
`

type UpdateAllocationParams struct {
	AllocationID string
	Reserved     int64
	Consumed     int64
	Revision     int64
}

func (q *Queries) UpdateAllocation(ctx context.Context, arg UpdateAllocationParams) error {
	_, err := q.db.Exec(ctx, updateAllocation,
		arg.AllocationID,
		arg.Reserved,
		arg.Consumed,
		arg.Revision,
	)
	return err
}

const updateDispatch = `-- name: UpdateDispatch :exec
UPDATE dispatches SET state = $2, outcome = $3, denial_code = $4, evidence_ref = $5, inventory_state = $6, inventory_version = $7, observed_at = $8
WHERE dispatch_id = $1
`

type UpdateDispatchParams struct {
	DispatchID       string
	State            string
	Outcome          *string
	DenialCode       *string
	EvidenceRef      *string
	InventoryState   string
	InventoryVersion *string
	ObservedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateDispatch(ctx context.Context, arg UpdateDispatchParams) error {
	_, err := q.db.Exec(ctx, updateDispatch,
		arg.DispatchID,
		arg.State,
		arg.Outcome,
		arg.DenialCode,
		arg.EvidenceRef,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.ObservedAt,
	)
	return err
}

const updatePool = `-- name: UpdatePool :exec
UPDATE budget_pools SET allocated = $2, revision = $3 WHERE pool_id = $1
`

type UpdatePoolParams struct {
	PoolID    string
	Allocated int64
	Revision  int64
}

func (q *Queries) UpdatePool(ctx context.Context, arg UpdatePoolParams) error {
	_, err := q.db.Exec(ctx, updatePool, arg.PoolID, arg.Allocated, arg.Revision)
	return err
}
