// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: effects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDisposition = `-- name: GetDisposition :one
SELECT disposition_id, class, obligation_id, tenant_id, run_id, recovery_epoch, command_id, actor_id, request_digest, decision, evidence_ref, evidence_digest, reason, decided_at FROM obligation_dispositions WHERE class = $1 AND obligation_id = $2
`

type GetDispositionParams struct {
	Class        string
	ObligationID string
}

func (q *Queries) GetDisposition(ctx context.Context, arg GetDispositionParams) (ObligationDisposition, error) {
	row := q.db.QueryRow(ctx, getDisposition, arg.Class, arg.ObligationID)
	var i ObligationDisposition
	err := row.Scan(
		&i.DispositionID,
		&i.Class,
		&i.ObligationID,
		&i.TenantID,
		&i.RunID,
		&i.RecoveryEpoch,
		&i.CommandID,
		&i.ActorID,
		&i.RequestDigest,
		&i.Decision,
		&i.EvidenceRef,
		&i.EvidenceDigest,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const getDispositionByCommand = `-- name: GetDispositionByCommand :one
SELECT disposition_id, class, obligation_id, tenant_id, run_id, recovery_epoch, command_id, actor_id, request_digest, decision, evidence_ref, evidence_digest, reason, decided_at FROM obligation_dispositions WHERE tenant_id = $1 AND command_id = $2
`

type GetDispositionByCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetDispositionByCommand(ctx context.Context, arg GetDispositionByCommandParams) (ObligationDisposition, error) {
	row := q.db.QueryRow(ctx, getDispositionByCommand, arg.TenantID, arg.CommandID)
	var i ObligationDisposition
	err := row.Scan(
		&i.DispositionID,
		&i.Class,
		&i.ObligationID,
		&i.TenantID,
		&i.RunID,
		&i.RecoveryEpoch,
		&i.CommandID,
		&i.ActorID,
		&i.RequestDigest,
		&i.Decision,
		&i.EvidenceRef,
		&i.EvidenceDigest,
		&i.Reason,
		&i.DecidedAt,
	)
	return i, err
}

const getEffect = `-- name: GetEffect :one
SELECT effect_id, operation_id, kind, occurrence, canonical_subject, request_digest, expected_revision, state, outcome_ref, query_ref, inventory_state, inventory_version, created_at, updated_at, tenant_id, attempt_id, command_id, owner, execution_epoch, recovery_epoch, lease_id, lease_fence, lease_expires_at, outcome, denial_code, deadline, observed_at FROM effect_intents WHERE effect_id = $1
`

func (q *Queries) GetEffect(ctx context.Context, effectID string) (EffectIntent, error) {
	row := q.db.QueryRow(ctx, getEffect, effectID)
	var i EffectIntent
	err := row.Scan(
		&i.EffectID,
		&i.OperationID,
		&i.Kind,
		&i.Occurrence,
		&i.CanonicalSubject,
		&i.RequestDigest,
		&i.ExpectedRevision,
		&i.State,
		&i.OutcomeRef,
		&i.QueryRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AttemptID,
		&i.CommandID,
		&i.Owner,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.Outcome,
		&i.DenialCode,
		&i.Deadline,
		&i.ObservedAt,
	)
	return i, err
}

const getEffectByCommand = `-- name: GetEffectByCommand :one

SELECT effect_id, operation_id, kind, occurrence, canonical_subject, request_digest, expected_revision, state, outcome_ref, query_ref, inventory_state, inventory_version, created_at, updated_at, tenant_id, attempt_id, command_id, owner, execution_epoch, recovery_epoch, lease_id, lease_fence, lease_expires_at, outcome, denial_code, deadline, observed_at FROM effect_intents WHERE tenant_id = $1 AND command_id = $2
`

type GetEffectByCommandParams struct {
	TenantID  string
	CommandID string
}

// Business-write obligations, their single-use permit, durable outcome
// observations and evidence-bound dispositions (DD-02 §5, DD-06 §3, P07).
// Lock ranks: operation (2), attempt (3), effect (6); the application
// performs the inventory write between its two transactions, never under
// these locks.
func (q *Queries) GetEffectByCommand(ctx context.Context, arg GetEffectByCommandParams) (EffectIntent, error) {
	row := q.db.QueryRow(ctx, getEffectByCommand, arg.TenantID, arg.CommandID)
	var i EffectIntent
	err := row.Scan(
		&i.EffectID,
		&i.OperationID,
		&i.Kind,
		&i.Occurrence,
		&i.CanonicalSubject,
		&i.RequestDigest,
		&i.ExpectedRevision,
		&i.State,
		&i.OutcomeRef,
		&i.QueryRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AttemptID,
		&i.CommandID,
		&i.Owner,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.Outcome,
		&i.DenialCode,
		&i.Deadline,
		&i.ObservedAt,
	)
	return i, err
}

const getEffectByOccurrence = `-- name: GetEffectByOccurrence :one
SELECT effect_id, operation_id, kind, occurrence, canonical_subject, request_digest, expected_revision, state, outcome_ref, query_ref, inventory_state, inventory_version, created_at, updated_at, tenant_id, attempt_id, command_id, owner, execution_epoch, recovery_epoch, lease_id, lease_fence, lease_expires_at, outcome, denial_code, deadline, observed_at FROM effect_intents WHERE operation_id = $1 AND kind = $2 AND occurrence = $3
`

type GetEffectByOccurrenceParams struct {
	OperationID string
	Kind        string
	Occurrence  int64
}

func (q *Queries) GetEffectByOccurrence(ctx context.Context, arg GetEffectByOccurrenceParams) (EffectIntent, error) {
	row := q.db.QueryRow(ctx, getEffectByOccurrence, arg.OperationID, arg.Kind, arg.Occurrence)
	var i EffectIntent
	err := row.Scan(
		&i.EffectID,
		&i.OperationID,
		&i.Kind,
		&i.Occurrence,
		&i.CanonicalSubject,
		&i.RequestDigest,
		&i.ExpectedRevision,
		&i.State,
		&i.OutcomeRef,
		&i.QueryRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AttemptID,
		&i.CommandID,
		&i.Owner,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.Outcome,
		&i.DenialCode,
		&i.Deadline,
		&i.ObservedAt,
	)
	return i, err
}

const getEffectObservation = `-- name: GetEffectObservation :one
SELECT observation_id, effect_id, source, sequence, outcome, receipt_digest, native_reference, observed_at FROM effect_observations WHERE effect_id = $1 AND source = $2 AND sequence = $3
`

type GetEffectObservationParams struct {
	EffectID string
	Source   string
	Sequence int64
}

func (q *Queries) GetEffectObservation(ctx context.Context, arg GetEffectObservationParams) (EffectObservation, error) {
	row := q.db.QueryRow(ctx, getEffectObservation, arg.EffectID, arg.Source, arg.Sequence)
	var i EffectObservation
	err := row.Scan(
		&i.ObservationID,
		&i.EffectID,
		&i.Source,
		&i.Sequence,
		&i.Outcome,
		&i.ReceiptDigest,
		&i.NativeReference,
		&i.ObservedAt,
	)
	return i, err
}

const hasUnresolvedEffect = `-- name: HasUnresolvedEffect :one
SELECT EXISTS (SELECT 1 FROM effect_intents WHERE operation_id = $1 AND state IN ('permitted', 'unknown'))
`

func (q *Queries) HasUnresolvedEffect(ctx context.Context, operationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnresolvedEffect, operationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertDisposition = `-- name: InsertDisposition :exec
INSERT INTO obligation_dispositions (
    disposition_id, class, obligation_id, tenant_id, run_id, recovery_epoch, command_id, actor_id, request_digest, decision,
    evidence_ref, evidence_digest, reason, decided_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertDispositionParams struct {
	DispositionID  string
	Class          string
	ObligationID   string
	TenantID       string
	RunID          *string
	RecoveryEpoch  int64
	CommandID      string
	ActorID        string
	RequestDigest  string
	Decision       string
	EvidenceRef    string
	EvidenceDigest string
	Reason         string
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDisposition(ctx context.Context, arg InsertDispositionParams) error {
	_, err := q.db.Exec(ctx, insertDisposition,
		arg.DispositionID,
		arg.Class,
		arg.ObligationID,
		arg.TenantID,
		arg.RunID,
		arg.RecoveryEpoch,
		arg.CommandID,
		arg.ActorID,
		arg.RequestDigest,
		arg.Decision,
		arg.EvidenceRef,
		arg.EvidenceDigest,
		arg.Reason,
		arg.DecidedAt,
	)
	return err
}

const insertEffect = `-- name: InsertEffect :exec
INSERT INTO effect_intents (
    effect_id, operation_id, kind, occurrence, canonical_subject, request_digest, expected_revision, state, outcome_ref, query_ref,
    inventory_state, inventory_version, created_at, updated_at, tenant_id, attempt_id, command_id, owner, execution_epoch, recovery_epoch,
    lease_id, lease_fence, lease_expires_at, outcome, denial_code, deadline, observed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27
)
`

type InsertEffectParams struct {
	EffectID         string
	OperationID      string
	Kind             string
	Occurrence       int64
	CanonicalSubject string
	RequestDigest    string
	ExpectedRevision *string
	State            string
	OutcomeRef       *string
	QueryRef         *string
	InventoryState   string
	InventoryVersion *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TenantID         string
	AttemptID        *string
	CommandID        string
	Owner            string
	ExecutionEpoch   int64
	RecoveryEpoch    int64
	LeaseID          *string
	LeaseFence       *int64
	LeaseExpiresAt   pgtype.Timestamptz
	Outcome          *string
	DenialCode       *string
	Deadline         pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
}

func (q *Queries) InsertEffect(ctx context.Context, arg InsertEffectParams) error {
	_, err := q.db.Exec(ctx, insertEffect,
		arg.EffectID,
		arg.OperationID,
		arg.Kind,
		arg.Occurrence,
		arg.CanonicalSubject,
		arg.RequestDigest,
		arg.ExpectedRevision,
		arg.State,
		arg.OutcomeRef,
		arg.QueryRef,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.AttemptID,
		arg.CommandID,
		arg.Owner,
		arg.ExecutionEpoch,
		arg.RecoveryEpoch,
		arg.LeaseID,
		arg.LeaseFence,
		arg.LeaseExpiresAt,
		arg.Outcome,
		arg.DenialCode,
		arg.Deadline,
		arg.ObservedAt,
	)
	return err
}

const insertEffectObservation = `-- name: InsertEffectObservation :exec
INSERT INTO effect_observations (observation_id, effect_id, source, sequence, outcome, receipt_digest, native_reference, observed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEffectObservationParams struct {
	ObservationID   string
	EffectID        string
	Source          string
	Sequence        int64
	Outcome         string
	ReceiptDigest   string
	NativeReference string
	ObservedAt      pgtype.Timestamptz
}

func (q *Queries) InsertEffectObservation(ctx context.Context, arg InsertEffectObservationParams) error {
	_, err := q.db.Exec(ctx, insertEffectObservation,
		arg.ObservationID,
		arg.EffectID,
		arg.Source,
		arg.Sequence,
		arg.Outcome,
		arg.ReceiptDigest,
		arg.NativeReference,
		arg.ObservedAt,
	)
	return err
}

const lockEffect = `-- name: LockEffect :one
SELECT effect_id, operation_id, kind, occurrence, canonical_subject, request_digest, expected_revision, state, outcome_ref, query_ref, inventory_state, inventory_version, created_at, updated_at, tenant_id, attempt_id, command_id, owner, execution_epoch, recovery_epoch, lease_id, lease_fence, lease_expires_at, outcome, denial_code, deadline, observed_at FROM effect_intents WHERE effect_id = $1 FOR UPDATE
`

func (q *Queries) LockEffect(ctx context.Context, effectID string) (EffectIntent, error) {
	row := q.db.QueryRow(ctx, lockEffect, effectID)
	var i EffectIntent
	err := row.Scan(
		&i.EffectID,
		&i.OperationID,
		&i.Kind,
		&i.Occurrence,
		&i.CanonicalSubject,
		&i.RequestDigest,
		&i.ExpectedRevision,
		&i.State,
		&i.OutcomeRef,
		&i.QueryRef,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.AttemptID,
		&i.CommandID,
		&i.Owner,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.Outcome,
		&i.DenialCode,
		&i.Deadline,
		&i.ObservedAt,
	)
	return i, err
}

const updateEffect = `-- name: UpdateEffect :exec
UPDATE effect_intents SET state = $2, outcome = $3, denial_code = $4, outcome_ref = $5, query_ref = $6, inventory_state = $7, inventory_version = $8,
    recovery_epoch = $9, observed_at = $10, updated_at = $11
WHERE effect_id = $1
`

type UpdateEffectParams struct {
	EffectID         string
	State            string
	Outcome          *string
	DenialCode       *string
	OutcomeRef       *string
	QueryRef         *string
	InventoryState   string
	InventoryVersion *string
	RecoveryEpoch    int64
	ObservedAt       pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateEffect(ctx context.Context, arg UpdateEffectParams) error {
	_, err := q.db.Exec(ctx, updateEffect,
		arg.EffectID,
		arg.State,
		arg.Outcome,
		arg.DenialCode,
		arg.OutcomeRef,
		arg.QueryRef,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.RecoveryEpoch,
		arg.ObservedAt,
		arg.UpdatedAt,
	)
	return err
}
