// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttempts = `-- name: CountAttempts :one
SELECT count(*) FROM attempts WHERE operation_id = $1 AND step_id = $2 AND visit_ordinal = $3
`

type CountAttemptsParams struct {
	OperationID  string
	StepID       string
	VisitOrdinal int64
}

func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttempts, arg.OperationID, arg.StepID, arg.VisitOrdinal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT attempt_id, operation_id, tenant_id, step_id, visit_ordinal, attempt_ordinal, profile_id, execution_epoch, command_id, request_digest, state, outcome, cleanup_state, failure_code, accepted_stage_id, deadline, created_at, updated_at FROM attempts WHERE attempt_id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, attemptID string) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, attemptID)
	var i Attempt
	err := row.Scan(
		&i.AttemptID,
		&i.OperationID,
		&i.TenantID,
		&i.StepID,
		&i.VisitOrdinal,
		&i.AttemptOrdinal,
		&i.ProfileID,
		&i.ExecutionEpoch,
		&i.CommandID,
		&i.RequestDigest,
		&i.State,
		&i.Outcome,
		&i.CleanupState,
		&i.FailureCode,
		&i.AcceptedStageID,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttemptByCommand = `-- name: GetAttemptByCommand :one
SELECT attempt_id, operation_id, tenant_id, step_id, visit_ordinal, attempt_ordinal, profile_id, execution_epoch, command_id, request_digest, state, outcome, cleanup_state, failure_code, accepted_stage_id, deadline, created_at, updated_at FROM attempts WHERE operation_id = $1 AND command_id = $2
`

type GetAttemptByCommandParams struct {
	OperationID string
	CommandID   string
}

func (q *Queries) GetAttemptByCommand(ctx context.Context, arg GetAttemptByCommandParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByCommand, arg.OperationID, arg.CommandID)
	var i Attempt
	err := row.Scan(
		&i.AttemptID,
		&i.OperationID,
		&i.TenantID,
		&i.StepID,
		&i.VisitOrdinal,
		&i.AttemptOrdinal,
		&i.ProfileID,
		&i.ExecutionEpoch,
		&i.CommandID,
		&i.RequestDigest,
		&i.State,
		&i.Outcome,
		&i.CleanupState,
		&i.FailureCode,
		&i.AcceptedStageID,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByPod = `-- name: GetInstanceByPod :one
SELECT instance_id, attempt_id, launch_id, launch_key, backend, job_uid, pod_uid, image_digest, launch_epoch, phase, exit_code, is_current, registered_at, observed_at FROM physical_instances WHERE backend = $1 AND pod_uid = $2
`

type GetInstanceByPodParams struct {
	Backend string
	PodUid  string
}

func (q *Queries) GetInstanceByPod(ctx context.Context, arg GetInstanceByPodParams) (PhysicalInstance, error) {
	row := q.db.QueryRow(ctx, getInstanceByPod, arg.Backend, arg.PodUid)
	var i PhysicalInstance
	err := row.Scan(
		&i.InstanceID,
		&i.AttemptID,
		&i.LaunchID,
		&i.LaunchKey,
		&i.Backend,
		&i.JobUid,
		&i.PodUid,
		&i.ImageDigest,
		&i.LaunchEpoch,
		&i.Phase,
		&i.ExitCode,
		&i.IsCurrent,
		&i.RegisteredAt,
		&i.ObservedAt,
	)
	return i, err
}

const getLaunch = `-- name: GetLaunch :one
SELECT launch_id, attempt_id, operation_id, launch_key, backend, profile_id, image_digest, execution_epoch, launch_epoch, deadline, command_id, request_digest, inventory_state, inventory_version, created_at, updated_at FROM launches WHERE launch_id = $1
`

func (q *Queries) GetLaunch(ctx context.Context, launchID string) (Launch, error) {
	row := q.db.QueryRow(ctx, getLaunch, launchID)
	var i Launch
	err := row.Scan(
		&i.LaunchID,
		&i.AttemptID,
		&i.OperationID,
		&i.LaunchKey,
		&i.Backend,
		&i.ProfileID,
		&i.ImageDigest,
		&i.ExecutionEpoch,
		&i.LaunchEpoch,
		&i.Deadline,
		&i.CommandID,
		&i.RequestDigest,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLaunchByCommand = `-- name: GetLaunchByCommand :one
SELECT launch_id, attempt_id, operation_id, launch_key, backend, profile_id, image_digest, execution_epoch, launch_epoch, deadline, command_id, request_digest, inventory_state, inventory_version, created_at, updated_at FROM launches WHERE attempt_id = $1 AND command_id = $2
`

type GetLaunchByCommandParams struct {
	AttemptID string
	CommandID string
}

func (q *Queries) GetLaunchByCommand(ctx context.Context, arg GetLaunchByCommandParams) (Launch, error) {
	row := q.db.QueryRow(ctx, getLaunchByCommand, arg.AttemptID, arg.CommandID)
	var i Launch
	err := row.Scan(
		&i.LaunchID,
		&i.AttemptID,
		&i.OperationID,
		&i.LaunchKey,
		&i.Backend,
		&i.ProfileID,
		&i.ImageDigest,
		&i.ExecutionEpoch,
		&i.LaunchEpoch,
		&i.Deadline,
		&i.CommandID,
		&i.RequestDigest,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLaunchByKey = `-- name: GetLaunchByKey :one
SELECT launch_id, attempt_id, operation_id, launch_key, backend, profile_id, image_digest, execution_epoch, launch_epoch, deadline, command_id, request_digest, inventory_state, inventory_version, created_at, updated_at FROM launches WHERE backend = $1 AND launch_key = $2
`

type GetLaunchByKeyParams struct {
	Backend   string
	LaunchKey string
}

func (q *Queries) GetLaunchByKey(ctx context.Context, arg GetLaunchByKeyParams) (Launch, error) {
	row := q.db.QueryRow(ctx, getLaunchByKey, arg.Backend, arg.LaunchKey)
	var i Launch
	err := row.Scan(
		&i.LaunchID,
		&i.AttemptID,
		&i.OperationID,
		&i.LaunchKey,
		&i.Backend,
		&i.ProfileID,
		&i.ImageDigest,
		&i.ExecutionEpoch,
		&i.LaunchEpoch,
		&i.Deadline,
		&i.CommandID,
		&i.RequestDigest,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStageByAttempt = `-- name: GetStageByAttempt :one
SELECT stage_id, attempt_id, instance_id, operation_id, phase_ordinal, profile_id, verdict, failure_code, result_digest, result_manifest, observer_identity, command_id, request_digest, accepted_at, result_manifest_bytes, execution_epoch, recovery_epoch FROM stage_manifests WHERE attempt_id = $1 AND phase_ordinal = 1
`

func (q *Queries) GetStageByAttempt(ctx context.Context, attemptID string) (StageManifest, error) {
	row := q.db.QueryRow(ctx, getStageByAttempt, attemptID)
	var i StageManifest
	err := row.Scan(
		&i.StageID,
		&i.AttemptID,
		&i.InstanceID,
		&i.OperationID,
		&i.PhaseOrdinal,
		&i.ProfileID,
		&i.Verdict,
		&i.FailureCode,
		&i.ResultDigest,
		&i.ResultManifest,
		&i.ObserverIdentity,
		&i.CommandID,
		&i.RequestDigest,
		&i.AcceptedAt,
		&i.ResultManifestBytes,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
	)
	return i, err
}

const hasCurrentInstance = `-- name: HasCurrentInstance :one
SELECT EXISTS (SELECT 1 FROM physical_instances WHERE attempt_id = $1 AND is_current)
`

func (q *Queries) HasCurrentInstance(ctx context.Context, attemptID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasCurrentInstance, attemptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasOpenAttempt = `-- name: HasOpenAttempt :one
SELECT EXISTS (SELECT 1 FROM attempts WHERE operation_id = $1 AND state <> 'closed')
`

func (q *Queries) HasOpenAttempt(ctx context.Context, operationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenAttempt, operationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasUnknownAttempt = `-- name: HasUnknownAttempt :one
SELECT EXISTS (SELECT 1 FROM attempts WHERE operation_id = $1 AND attempt_id <> $2
    AND (cleanup_state = 'unknown' OR outcome = 'unknown'))
`

type HasUnknownAttemptParams struct {
	OperationID string
	AttemptID   string
}

func (q *Queries) HasUnknownAttempt(ctx context.Context, arg HasUnknownAttemptParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnknownAttempt, arg.OperationID, arg.AttemptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO attempts (
    attempt_id, operation_id, tenant_id, step_id, visit_ordinal, attempt_ordinal, profile_id, execution_epoch,
    command_id, request_digest, state, outcome, cleanup_state, failure_code, accepted_stage_id, deadline, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertAttemptParams struct {
	AttemptID       string
	OperationID     string
	TenantID        string
	StepID          string
	VisitOrdinal    int64
	AttemptOrdinal  int64
	ProfileID       string
	ExecutionEpoch  int64
	CommandID       string
	RequestDigest   string
	State           string
	Outcome         *string
	CleanupState    *string
	FailureCode     *string
	AcceptedStageID *string
	Deadline        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.AttemptID,
		arg.OperationID,
		arg.TenantID,
		arg.StepID,
		arg.VisitOrdinal,
		arg.AttemptOrdinal,
		arg.ProfileID,
		arg.ExecutionEpoch,
		arg.CommandID,
		arg.RequestDigest,
		arg.State,
		arg.Outcome,
		arg.CleanupState,
		arg.FailureCode,
		arg.AcceptedStageID,
		arg.Deadline,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertInstance = `-- name: InsertInstance :exec
INSERT INTO physical_instances (
    instance_id, attempt_id, launch_id, launch_key, backend, job_uid, pod_uid, image_digest, launch_epoch, phase, exit_code,
    is_current, registered_at, observed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertInstanceParams struct {
	InstanceID   string
	AttemptID    string
	LaunchID     string
	LaunchKey    string
	Backend      string
	JobUid       string
	PodUid       string
	ImageDigest  string
	LaunchEpoch  int64
	Phase        string
	ExitCode     *int32
	IsCurrent    bool
	RegisteredAt pgtype.Timestamptz
	ObservedAt   pgtype.Timestamptz
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) error {
	_, err := q.db.Exec(ctx, insertInstance,
		arg.InstanceID,
		arg.AttemptID,
		arg.LaunchID,
		arg.LaunchKey,
		arg.Backend,
		arg.JobUid,
		arg.PodUid,
		arg.ImageDigest,
		arg.LaunchEpoch,
		arg.Phase,
		arg.ExitCode,
		arg.IsCurrent,
		arg.RegisteredAt,
		arg.ObservedAt,
	)
	return err
}

const insertLaunch = `-- name: InsertLaunch :exec
INSERT INTO launches (
    launch_id, attempt_id, operation_id, launch_key, backend, profile_id, image_digest, execution_epoch, launch_epoch,
    deadline, command_id, request_digest, inventory_state, inventory_version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertLaunchParams struct {
	LaunchID         string
	AttemptID        string
	OperationID      string
	LaunchKey        string
	Backend          string
	ProfileID        string
	ImageDigest      string
	ExecutionEpoch   int64
	LaunchEpoch      int64
	Deadline         pgtype.Timestamptz
	CommandID        string
	RequestDigest    string
	InventoryState   string
	InventoryVersion *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertLaunch(ctx context.Context, arg InsertLaunchParams) error {
	_, err := q.db.Exec(ctx, insertLaunch,
		arg.LaunchID,
		arg.AttemptID,
		arg.OperationID,
		arg.LaunchKey,
		arg.Backend,
		arg.ProfileID,
		arg.ImageDigest,
		arg.ExecutionEpoch,
		arg.LaunchEpoch,
		arg.Deadline,
		arg.CommandID,
		arg.RequestDigest,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStage = `-- name: InsertStage :exec
INSERT INTO stage_manifests (
    stage_id, attempt_id, instance_id, operation_id, phase_ordinal, profile_id, verdict, failure_code, result_digest,
    result_manifest, result_manifest_bytes, observer_identity, command_id, request_digest, accepted_at, execution_epoch, recovery_epoch
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type InsertStageParams struct {
	StageID             string
	AttemptID           string
	InstanceID          string
	OperationID         string
	PhaseOrdinal        int64
	ProfileID           string
	Verdict             string
	FailureCode         *string
	ResultDigest        string
	ResultManifest      []byte
	ResultManifestBytes []byte
	ObserverIdentity    string
	CommandID           string
	RequestDigest       string
	AcceptedAt          pgtype.Timestamptz
	ExecutionEpoch      int64
	RecoveryEpoch       int64
}

func (q *Queries) InsertStage(ctx context.Context, arg InsertStageParams) error {
	_, err := q.db.Exec(ctx, insertStage,
		arg.StageID,
		arg.AttemptID,
		arg.InstanceID,
		arg.OperationID,
		arg.PhaseOrdinal,
		arg.ProfileID,
		arg.Verdict,
		arg.FailureCode,
		arg.ResultDigest,
		arg.ResultManifest,
		arg.ResultManifestBytes,
		arg.ObserverIdentity,
		arg.CommandID,
		arg.RequestDigest,
		arg.AcceptedAt,
		arg.ExecutionEpoch,
		arg.RecoveryEpoch,
	)
	return err
}

const lockAttempt = `-- name: LockAttempt :one
SELECT attempt_id, operation_id, tenant_id, step_id, visit_ordinal, attempt_ordinal, profile_id, execution_epoch, command_id, request_digest, state, outcome, cleanup_state, failure_code, accepted_stage_id, deadline, created_at, updated_at FROM attempts WHERE attempt_id = $1 FOR UPDATE
`

func (q *Queries) LockAttempt(ctx context.Context, attemptID string) (Attempt, error) {
	row := q.db.QueryRow(ctx, lockAttempt, attemptID)
	var i Attempt
	err := row.Scan(
		&i.AttemptID,
		&i.OperationID,
		&i.TenantID,
		&i.StepID,
		&i.VisitOrdinal,
		&i.AttemptOrdinal,
		&i.ProfileID,
		&i.ExecutionEpoch,
		&i.CommandID,
		&i.RequestDigest,
		&i.State,
		&i.Outcome,
		&i.CleanupState,
		&i.FailureCode,
		&i.AcceptedStageID,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockInstance = `-- name: LockInstance :one
SELECT instance_id, attempt_id, launch_id, launch_key, backend, job_uid, pod_uid, image_digest, launch_epoch, phase, exit_code, is_current, registered_at, observed_at FROM physical_instances WHERE instance_id = $1 FOR UPDATE
`

func (q *Queries) LockInstance(ctx context.Context, instanceID string) (PhysicalInstance, error) {
	row := q.db.QueryRow(ctx, lockInstance, instanceID)
	var i PhysicalInstance
	err := row.Scan(
		&i.InstanceID,
		&i.AttemptID,
		&i.LaunchID,
		&i.LaunchKey,
		&i.Backend,
		&i.JobUid,
		&i.PodUid,
		&i.ImageDigest,
		&i.LaunchEpoch,
		&i.Phase,
		&i.ExitCode,
		&i.IsCurrent,
		&i.RegisteredAt,
		&i.ObservedAt,
	)
	return i, err
}

const lockLaunch = `-- name: LockLaunch :one
SELECT launch_id, attempt_id, operation_id, launch_key, backend, profile_id, image_digest, execution_epoch, launch_epoch, deadline, command_id, request_digest, inventory_state, inventory_version, created_at, updated_at FROM launches WHERE launch_id = $1 FOR UPDATE
`

func (q *Queries) LockLaunch(ctx context.Context, launchID string) (Launch, error) {
	row := q.db.QueryRow(ctx, lockLaunch, launchID)
	var i Launch
	err := row.Scan(
		&i.LaunchID,
		&i.AttemptID,
		&i.OperationID,
		&i.LaunchKey,
		&i.Backend,
		&i.ProfileID,
		&i.ImageDigest,
		&i.ExecutionEpoch,
		&i.LaunchEpoch,
		&i.Deadline,
		&i.CommandID,
		&i.RequestDigest,
		&i.InventoryState,
		&i.InventoryVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttempt = `-- name: UpdateAttempt :exec
UPDATE attempts SET state = $2, outcome = $3, cleanup_state = $4, failure_code = $5, accepted_stage_id = $6, updated_at = $7
WHERE attempt_id = $1
`

type UpdateAttemptParams struct {
	AttemptID       string
	State           string
	Outcome         *string
	CleanupState    *string
	FailureCode     *string
	AcceptedStageID *string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) error {
	_, err := q.db.Exec(ctx, updateAttempt,
		arg.AttemptID,
		arg.State,
		arg.Outcome,
		arg.CleanupState,
		arg.FailureCode,
		arg.AcceptedStageID,
		arg.UpdatedAt,
	)
	return err
}

const updateInstanceObservation = `-- name: UpdateInstanceObservation :exec
UPDATE physical_instances SET phase = $2, exit_code = $3, observed_at = $4 WHERE instance_id = $1
`

type UpdateInstanceObservationParams struct {
	InstanceID string
	Phase      string
	ExitCode   *int32
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) UpdateInstanceObservation(ctx context.Context, arg UpdateInstanceObservationParams) error {
	_, err := q.db.Exec(ctx, updateInstanceObservation,
		arg.InstanceID,
		arg.Phase,
		arg.ExitCode,
		arg.ObservedAt,
	)
	return err
}

const updateLaunchInventory = `-- name: UpdateLaunchInventory :exec
UPDATE launches SET inventory_state = $2, inventory_version = $3, updated_at = $4 WHERE launch_id = $1
`

type UpdateLaunchInventoryParams struct {
	LaunchID         string
	InventoryState   string
	InventoryVersion *string
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateLaunchInventory(ctx context.Context, arg UpdateLaunchInventoryParams) error {
	_, err := q.db.Exec(ctx, updateLaunchInventory,
		arg.LaunchID,
		arg.InventoryState,
		arg.InventoryVersion,
		arg.UpdatedAt,
	)
	return err
}
