// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePermits = `-- name: CountActivePermits :one
SELECT count(*) FROM permits WHERE pool_id = $1 AND state = 'active'
`

func (q *Queries) CountActivePermits(ctx context.Context, poolID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePermits, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivePermitsBefore = `-- name: CountActivePermitsBefore :one
SELECT count(*) FROM permits WHERE pool_id = $1 AND state = 'active' AND granted_at < $2
`

type CountActivePermitsBeforeParams struct {
	PoolID    string
	GrantedAt pgtype.Timestamptz
}

func (q *Queries) CountActivePermitsBefore(ctx context.Context, arg CountActivePermitsBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePermitsBefore, arg.PoolID, arg.GrantedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivePermit = `-- name: GetActivePermit :one
SELECT permit_id, pool_id, owner_kind, owner_id, fence_epoch, state, granted_at, released_at, release_evidence FROM permits WHERE pool_id = $1 AND owner_kind = $2 AND owner_id = $3 AND state = 'active'
`

type GetActivePermitParams struct {
	PoolID    string
	OwnerKind string
	OwnerID   string
}

func (q *Queries) GetActivePermit(ctx context.Context, arg GetActivePermitParams) (Permit, error) {
	row := q.db.QueryRow(ctx, getActivePermit, arg.PoolID, arg.OwnerKind, arg.OwnerID)
	var i Permit
	err := row.Scan(
		&i.PermitID,
		&i.PoolID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.FenceEpoch,
		&i.State,
		&i.GrantedAt,
		&i.ReleasedAt,
		&i.ReleaseEvidence,
	)
	return i, err
}

const getFunding = `-- name: GetFunding :one
SELECT operation_id, command_id, request_digest, currency, amount, funded_at FROM fundings WHERE operation_id = $1
`

func (q *Queries) GetFunding(ctx context.Context, operationID string) (Funding, error) {
	row := q.db.QueryRow(ctx, getFunding, operationID)
	var i Funding
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.RequestDigest,
		&i.Currency,
		&i.Amount,
		&i.FundedAt,
	)
	return i, err
}

const getOperationSettlement = `-- name: GetOperationSettlement :one
SELECT operation_id, command_id, request_digest, outcome, failure_code, phase FROM operation_settlements WHERE operation_id = $1
`

func (q *Queries) GetOperationSettlement(ctx context.Context, operationID string) (OperationSettlement, error) {
	row := q.db.QueryRow(ctx, getOperationSettlement, operationID)
	var i OperationSettlement
	err := row.Scan(
		&i.OperationID,
		&i.CommandID,
		&i.RequestDigest,
		&i.Outcome,
		&i.FailureCode,
		&i.Phase,
	)
	return i, err
}

const getPermitByOwner = `-- name: GetPermitByOwner :one
SELECT permit_id, pool_id, owner_kind, owner_id, fence_epoch, state, granted_at, released_at, release_evidence FROM permits WHERE owner_kind = $1 AND owner_id = $2 ORDER BY granted_at DESC LIMIT 1
`

type GetPermitByOwnerParams struct {
	OwnerKind string
	OwnerID   string
}

func (q *Queries) GetPermitByOwner(ctx context.Context, arg GetPermitByOwnerParams) (Permit, error) {
	row := q.db.QueryRow(ctx, getPermitByOwner, arg.OwnerKind, arg.OwnerID)
	var i Permit
	err := row.Scan(
		&i.PermitID,
		&i.PoolID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.FenceEpoch,
		&i.State,
		&i.GrantedAt,
		&i.ReleasedAt,
		&i.ReleaseEvidence,
	)
	return i, err
}

const getStageArtifactByTransfer = `-- name: GetStageArtifactByTransfer :one
SELECT sa.stage_id, sa.transfer_id, sa.handle, sa.class, sa.digest, sa.size_bytes, sa.object_version FROM stage_artifacts sa JOIN stage_manifests sm ON sm.stage_id = sa.stage_id
WHERE sa.transfer_id = $1 AND sm.operation_id = $2 LIMIT 1
`

type GetStageArtifactByTransferParams struct {
	TransferID  string
	OperationID string
}

func (q *Queries) GetStageArtifactByTransfer(ctx context.Context, arg GetStageArtifactByTransferParams) (StageArtifact, error) {
	row := q.db.QueryRow(ctx, getStageArtifactByTransfer, arg.TransferID, arg.OperationID)
	var i StageArtifact
	err := row.Scan(
		&i.StageID,
		&i.TransferID,
		&i.Handle,
		&i.Class,
		&i.Digest,
		&i.SizeBytes,
		&i.ObjectVersion,
	)
	return i, err
}

const insertFunding = `-- name: InsertFunding :exec
INSERT INTO fundings (operation_id, command_id, request_digest, currency, amount, funded_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFundingParams struct {
	OperationID   string
	CommandID     string
	RequestDigest string
	Currency      string
	Amount        int64
	FundedAt      pgtype.Timestamptz
}

func (q *Queries) InsertFunding(ctx context.Context, arg InsertFundingParams) error {
	_, err := q.db.Exec(ctx, insertFunding,
		arg.OperationID,
		arg.CommandID,
		arg.RequestDigest,
		arg.Currency,
		arg.Amount,
		arg.FundedAt,
	)
	return err
}

const insertOperationSettlement = `-- name: InsertOperationSettlement :exec
INSERT INTO operation_settlements (operation_id, command_id, request_digest, outcome, failure_code, phase)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOperationSettlementParams struct {
	OperationID   string
	CommandID     string
	RequestDigest string
	Outcome       string
	FailureCode   string
	Phase         string
}

func (q *Queries) InsertOperationSettlement(ctx context.Context, arg InsertOperationSettlementParams) error {
	_, err := q.db.Exec(ctx, insertOperationSettlement,
		arg.OperationID,
		arg.CommandID,
		arg.RequestDigest,
		arg.Outcome,
		arg.FailureCode,
		arg.Phase,
	)
	return err
}

const insertPermit = `-- name: InsertPermit :exec
INSERT INTO permits (permit_id, pool_id, owner_kind, owner_id, fence_epoch, state, granted_at, released_at, release_evidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPermitParams struct {
	PermitID        string
	PoolID          string
	OwnerKind       string
	OwnerID         string
	FenceEpoch      int64
	State           string
	GrantedAt       pgtype.Timestamptz
	ReleasedAt      pgtype.Timestamptz
	ReleaseEvidence *string
}

func (q *Queries) InsertPermit(ctx context.Context, arg InsertPermitParams) error {
	_, err := q.db.Exec(ctx, insertPermit,
		arg.PermitID,
		arg.PoolID,
		arg.OwnerKind,
		arg.OwnerID,
		arg.FenceEpoch,
		arg.State,
		arg.GrantedAt,
		arg.ReleasedAt,
		arg.ReleaseEvidence,
	)
	return err
}

const listStagesByOperation = `-- name: ListStagesByOperation :many
SELECT stage_id, attempt_id, instance_id, operation_id, phase_ordinal, profile_id, verdict, failure_code, result_digest, result_manifest, observer_identity, command_id, request_digest, accepted_at, result_manifest_bytes, execution_epoch, recovery_epoch FROM stage_manifests WHERE operation_id = $1 ORDER BY accepted_at
`

func (q *Queries) ListStagesByOperation(ctx context.Context, operationID string) ([]StageManifest, error) {
	rows, err := q.db.Query(ctx, listStagesByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageManifest{}
	for rows.Next() {
		var i StageManifest
		if err := rows.Scan(
			&i.StageID,
			&i.AttemptID,
			&i.InstanceID,
			&i.OperationID,
			&i.PhaseOrdinal,
			&i.ProfileID,
			&i.Verdict,
			&i.FailureCode,
			&i.ResultDigest,
			&i.ResultManifest,
			&i.ObserverIdentity,
			&i.CommandID,
			&i.RequestDigest,
			&i.AcceptedAt,
			&i.ResultManifestBytes,
			&i.ExecutionEpoch,
			&i.RecoveryEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResourcePool = `-- name: LockResourcePool :one
SELECT pool_id, class, capacity, reserved_control FROM resource_pools WHERE pool_id = $1 FOR UPDATE
`

func (q *Queries) LockResourcePool(ctx context.Context, poolID string) (ResourcePool, error) {
	row := q.db.QueryRow(ctx, lockResourcePool, poolID)
	var i ResourcePool
	err := row.Scan(
		&i.PoolID,
		&i.Class,
		&i.Capacity,
		&i.ReservedControl,
	)
	return i, err
}

const releasePermits = `-- name: ReleasePermits :exec
UPDATE permits SET state = 'released', released_at = $3, release_evidence = $4
WHERE owner_kind = $1 AND owner_id = $2 AND state = 'active'
`

type ReleasePermitsParams struct {
	OwnerKind       string
	OwnerID         string
	ReleasedAt      pgtype.Timestamptz
	ReleaseEvidence *string
}

func (q *Queries) ReleasePermits(ctx context.Context, arg ReleasePermitsParams) error {
	_, err := q.db.Exec(ctx, releasePermits,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ReleasedAt,
		arg.ReleaseEvidence,
	)
	return err
}

const upsertResourcePool = `-- name: UpsertResourcePool :exec
INSERT INTO resource_pools (pool_id, class, capacity, reserved_control) VALUES ($1, $2, $3, $4)
ON CONFLICT (pool_id) DO UPDATE SET class = EXCLUDED.class, capacity = EXCLUDED.capacity, reserved_control = EXCLUDED.reserved_control
`

type UpsertResourcePoolParams struct {
	PoolID          string
	Class           string
	Capacity        int32
	ReservedControl int32
}

func (q *Queries) UpsertResourcePool(ctx context.Context, arg UpsertResourcePoolParams) error {
	_, err := q.db.Exec(ctx, upsertResourcePool,
		arg.PoolID,
		arg.Class,
		arg.Capacity,
		arg.ReservedControl,
	)
	return err
}
