// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdmissionClosure struct {
	ScopeKey   string
	RunID      string
	ClosedAt   pgtype.Timestamptz
	ReopenedAt pgtype.Timestamptz
}

type Allocation struct {
	AllocationID string
	PoolID       string
	OperationID  string
	Currency     string
	Amount       int64
	Reserved     int64
	Consumed     int64
	Revision     int64
	CreatedAt    pgtype.Timestamptz
}

type Answer struct {
	AnswerID            string
	OperationID         string
	TenantID            string
	ActorID             string
	QuestionSetID       string
	QuestionSetRevision int64
	TransferID          string
	Digest              string
	Handle              string
	UpdateID            string
	CommandID           string
	RequestDigest       string
	RelayState          string
	AcceptedAt          pgtype.Timestamptz
	RelayedAt           pgtype.Timestamptz
}

type ArtifactTransfer struct {
	TransferID            string
	TenantID              string
	OperationID           *string
	AttemptID             *string
	Class                 string
	MediaType             string
	ExpectedDigest        string
	ExpectedSize          int64
	Handle                string
	State                 string
	ObjectVersion         *string
	ReasonCode            *string
	CommandID             string
	RequestDigest         string
	Deadline              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	FinalizedAt           pgtype.Timestamptz
	ActorID               string
	ExecutionEpoch        int64
	RecoveryEpoch         int64
	ObjectKey             string
	ActualSize            *int64
	ActualDigest          *string
	FinalizeCommandID     *string
	FinalizeRequestDigest *string
	UpdatedAt             pgtype.Timestamptz
}

type Attempt struct {
	AttemptID       string
	OperationID     string
	TenantID        string
	StepID          string
	VisitOrdinal    int64
	AttemptOrdinal  int64
	ProfileID       string
	ExecutionEpoch  int64
	CommandID       string
	RequestDigest   string
	State           string
	Outcome         *string
	CleanupState    *string
	FailureCode     *string
	AcceptedStageID *string
	Deadline        pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Brief struct {
	BriefID            string
	OperationID        string
	TenantID           string
	Revision           int64
	TransferID         string
	Digest             string
	Handle             string
	RequirementsDigest string
	SourceRevisions    []byte
	BrandDigests       []byte
	AssetDigests       []byte
	State              string
	CommandID          string
	RequestDigest      string
	FrozenAt           pgtype.Timestamptz
}

type BudgetPool struct {
	PoolID      string
	Level       string
	TenantID    *string
	ActorID     *string
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	Currency    string
	CapAmount   int64
	Allocated   int64
	Revision    int64
}

type CostEntry struct {
	EntryID       string
	OperationID   string
	DispatchID    *string
	ObservationID *string
	Kind          string
	Currency      string
	Amount        int64
	CorrectionOf  *string
	CreatedAt     pgtype.Timestamptz
}

type Dispatch struct {
	DispatchID       string
	Kind             string
	TenantID         string
	OperationID      string
	AttemptID        string
	InstanceID       *string
	CallID           string
	Owner            string
	RequestDigest    string
	RouteID          *string
	GrantID          *string
	GrantRevision    *int64
	ExecutionEpoch   int64
	State            string
	Outcome          *string
	ReservedCurrency string
	ReservedAmount   int64
	MeterRevision    string
	SupersedesCallID *string
	EvidenceRef      *string
	InventoryState   string
	InventoryVersion *string
	Deadline         pgtype.Timestamptz
	AdmittedAt       pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
	DenialCode       *string
}

type EffectIntent struct {
	EffectID         string
	OperationID      string
	Kind             string
	Occurrence       int64
	CanonicalSubject string
	RequestDigest    string
	ExpectedRevision *string
	State            string
	OutcomeRef       *string
	QueryRef         *string
	InventoryState   string
	InventoryVersion *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TenantID         string
	AttemptID        *string
	CommandID        string
	Owner            string
	ExecutionEpoch   int64
	RecoveryEpoch    int64
	LeaseID          *string
	LeaseFence       *int64
	LeaseExpiresAt   pgtype.Timestamptz
	Outcome          *string
	DenialCode       *string
	Deadline         pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
}

type EffectObservation struct {
	ObservationID   string
	EffectID        string
	Source          string
	Sequence        int64
	Outcome         string
	ReceiptDigest   string
	NativeReference string
	ObservedAt      pgtype.Timestamptz
}

type Funding struct {
	OperationID   string
	CommandID     string
	RequestDigest string
	Currency      string
	Amount        int64
	FundedAt      pgtype.Timestamptz
}

type GrantPolicy struct {
	GrantID         string
	GrantRevision   int64
	TenantID        string
	PolicyDigest    string
	ServerID        string
	Methods         []string
	CostCapCurrency *string
	CostCapAmount   *int64
	ExpiresAt       pgtype.Timestamptz
	PolicyEpoch     int64
	ReceiptID       string
	RevocationState string
	FencedAt        pgtype.Timestamptz
	ConvergedAt     pgtype.Timestamptz
	RegisteredAt    pgtype.Timestamptz
}

type Launch struct {
	LaunchID         string
	AttemptID        string
	OperationID      string
	LaunchKey        string
	Backend          string
	ProfileID        string
	ImageDigest      string
	ExecutionEpoch   int64
	LaunchEpoch      int64
	Deadline         pgtype.Timestamptz
	CommandID        string
	RequestDigest    string
	InventoryState   string
	InventoryVersion *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ObligationDisposition struct {
	DispositionID  string
	Class          string
	ObligationID   string
	TenantID       string
	RunID          *string
	RecoveryEpoch  int64
	CommandID      string
	ActorID        string
	RequestDigest  string
	Decision       string
	EvidenceRef    string
	EvidenceDigest string
	Reason         string
	DecidedAt      pgtype.Timestamptz
}

type Operation struct {
	OperationID          string
	TenantID             string
	ProjectID            string
	ActorID              string
	CommandID            string
	Kind                 string
	ProfileID            string
	SubjectDigest        string
	BriefID              *string
	SourceRevision       *string
	SemanticDigest       string
	Lifecycle            string
	Phase                string
	ControlState         string
	CleanupState         string
	FinanceState         string
	FailureCode          *string
	Revision             int64
	NextEventSeq         int64
	ExecutionEpoch       int64
	RecoveryEpoch        int64
	Deadline             pgtype.Timestamptz
	IntakeState          string
	IntakeVersion        *string
	RelayState           string
	RelayRunID           *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ActiveDeadline       pgtype.Timestamptz
	LeaseState           string
	LeaseID              *string
	LeaseFence           *int64
	LeaseExpiresAt       pgtype.Timestamptz
	LeaseOccurrence      int64
	DefinitionActivation string
	PromptTransferID     *string
	PromptDigest         *string
	BrandReferences      []byte
	AssetReferences      []byte
	CandidateEffectID    *string
}

type OperationCommand struct {
	TenantID                   string
	CommandID                  string
	OperationID                string
	ActorID                    string
	Kind                       string
	ExpectedRevision           int64
	RequestDigest              string
	TargetDefinitionActivation *string
	Outcome                    string
	ReasonCode                 *string
	OperationRevision          int64
	AcceptedAt                 pgtype.Timestamptz
	SettledAt                  pgtype.Timestamptz
	RelayState                 string
}

type OperationEvent struct {
	OperationID  string
	EventSeq     int64
	TransitionID string
	EventType    string
	Revision     int64
	Payload      []byte
	OccurredAt   pgtype.Timestamptz
}

type Permit struct {
	PermitID        string
	PoolID          string
	OwnerKind       string
	OwnerID         string
	FenceEpoch      int64
	State           string
	GrantedAt       pgtype.Timestamptz
	ReleasedAt      pgtype.Timestamptz
	ReleaseEvidence *string
}

type PhysicalInstance struct {
	InstanceID   string
	AttemptID    string
	LaunchID     string
	LaunchKey    string
	Backend      string
	JobUid       string
	PodUid       string
	ImageDigest  string
	LaunchEpoch  int64
	Phase        string
	ExitCode     *int32
	IsCurrent    bool
	RegisteredAt pgtype.Timestamptz
	ObservedAt   pgtype.Timestamptz
}

type QuestionSet struct {
	QuestionSetID string
	OperationID   string
	TenantID      string
	Revision      int64
	Round         int64
	Questions     []byte
	State         string
	CommandID     string
	RequestDigest string
	AskedAt       pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

type RecoveryFinding struct {
	FindingID        string
	RunID            string
	Class            string
	ObligationID     string
	TenantID         string
	InventoryKey     string
	InventoryVersion string
	RecordedAt       pgtype.Timestamptz
	Status           string
	Outcome          string
	EvidenceRef      string
	Detail           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RecoveryProgress struct {
	RunID    string
	Class    string
	Cursor   string
	Complete bool
	Seen     int64
}

type RecoveryRun struct {
	RunID         string
	ScopeKey      string
	TenantID      string
	CommandID     string
	ActorID       string
	RequestDigest string
	RecoveryEpoch int64
	Phase         string
	WindowStart   pgtype.Timestamptz
	WindowEnd     pgtype.Timestamptz
	SkewMicros    int64
	Reason        string
	FencedCount   int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ReopenedAt    pgtype.Timestamptz
}

type ResourcePool struct {
	PoolID          string
	Class           string
	Capacity        int32
	ReservedControl int32
}

type StageArtifact struct {
	StageID       string
	TransferID    string
	Handle        string
	Class         string
	Digest        string
	SizeBytes     int64
	ObjectVersion string
}

type StageManifest struct {
	StageID             string
	AttemptID           string
	InstanceID          string
	OperationID         string
	PhaseOrdinal        int64
	ProfileID           string
	Verdict             string
	FailureCode         *string
	ResultDigest        string
	ResultManifest      []byte
	ObserverIdentity    string
	CommandID           string
	RequestDigest       string
	AcceptedAt          pgtype.Timestamptz
	ResultManifestBytes []byte
	ExecutionEpoch      int64
	RecoveryEpoch       int64
}

type UsageObservation struct {
	ObservationID    string
	DispatchID       string
	Source           string
	Sequence         int64
	NativeReference  string
	InputUnits       int64
	OutputUnits      int64
	ReasoningUnits   int64
	CachedInputUnits int64
	CostRevision     string
	ObservedAt       pgtype.Timestamptz
	UsageReported    bool
}
