// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommand = `-- name: GetCommand :one
SELECT tenant_id, command_id, operation_id, actor_id, kind, expected_revision, request_digest, target_definition_activation, outcome, reason_code, operation_revision, accepted_at, settled_at, relay_state FROM operation_commands WHERE tenant_id = $1 AND command_id = $2
`

type GetCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetCommand(ctx context.Context, arg GetCommandParams) (OperationCommand, error) {
	row := q.db.QueryRow(ctx, getCommand, arg.TenantID, arg.CommandID)
	var i OperationCommand
	err := row.Scan(
		&i.TenantID,
		&i.CommandID,
		&i.OperationID,
		&i.ActorID,
		&i.Kind,
		&i.ExpectedRevision,
		&i.RequestDigest,
		&i.TargetDefinitionActivation,
		&i.Outcome,
		&i.ReasonCode,
		&i.OperationRevision,
		&i.AcceptedAt,
		&i.SettledAt,
		&i.RelayState,
	)
	return i, err
}

const getOperationByCommand = `-- name: GetOperationByCommand :one
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at, active_deadline, lease_state, lease_id, lease_fence, lease_expires_at, lease_occurrence, definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references, candidate_effect_id FROM operations WHERE tenant_id = $1 AND command_id = $2
`

type GetOperationByCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetOperationByCommand(ctx context.Context, arg GetOperationByCommandParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByCommand, arg.TenantID, arg.CommandID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.ProjectID,
		&i.ActorID,
		&i.CommandID,
		&i.Kind,
		&i.ProfileID,
		&i.SubjectDigest,
		&i.BriefID,
		&i.SourceRevision,
		&i.SemanticDigest,
		&i.Lifecycle,
		&i.Phase,
		&i.ControlState,
		&i.CleanupState,
		&i.FinanceState,
		&i.FailureCode,
		&i.Revision,
		&i.NextEventSeq,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.Deadline,
		&i.IntakeState,
		&i.IntakeVersion,
		&i.RelayState,
		&i.RelayRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveDeadline,
		&i.LeaseState,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.LeaseOccurrence,
		&i.DefinitionActivation,
		&i.PromptTransferID,
		&i.PromptDigest,
		&i.BrandReferences,
		&i.AssetReferences,
		&i.CandidateEffectID,
	)
	return i, err
}

const getOperationScoped = `-- name: GetOperationScoped :one
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at, active_deadline, lease_state, lease_id, lease_fence, lease_expires_at, lease_occurrence, definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references, candidate_effect_id FROM operations WHERE operation_id = $1 AND tenant_id = $2
`

type GetOperationScopedParams struct {
	OperationID string
	TenantID    string
}

func (q *Queries) GetOperationScoped(ctx context.Context, arg GetOperationScopedParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationScoped, arg.OperationID, arg.TenantID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.ProjectID,
		&i.ActorID,
		&i.CommandID,
		&i.Kind,
		&i.ProfileID,
		&i.SubjectDigest,
		&i.BriefID,
		&i.SourceRevision,
		&i.SemanticDigest,
		&i.Lifecycle,
		&i.Phase,
		&i.ControlState,
		&i.CleanupState,
		&i.FinanceState,
		&i.FailureCode,
		&i.Revision,
		&i.NextEventSeq,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.Deadline,
		&i.IntakeState,
		&i.IntakeVersion,
		&i.RelayState,
		&i.RelayRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveDeadline,
		&i.LeaseState,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.LeaseOccurrence,
		&i.DefinitionActivation,
		&i.PromptTransferID,
		&i.PromptDigest,
		&i.BrandReferences,
		&i.AssetReferences,
		&i.CandidateEffectID,
	)
	return i, err
}

const insertCommand = `-- name: InsertCommand :exec
INSERT INTO operation_commands (
    tenant_id, command_id, operation_id, actor_id, kind, expected_revision, request_digest, target_definition_activation,
    outcome, reason_code, operation_revision, accepted_at, settled_at, relay_state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertCommandParams struct {
	TenantID                   string
	CommandID                  string
	OperationID                string
	ActorID                    string
	Kind                       string
	ExpectedRevision           int64
	RequestDigest              string
	TargetDefinitionActivation *string
	Outcome                    string
	ReasonCode                 *string
	OperationRevision          int64
	AcceptedAt                 pgtype.Timestamptz
	SettledAt                  pgtype.Timestamptz
	RelayState                 string
}

func (q *Queries) InsertCommand(ctx context.Context, arg InsertCommandParams) error {
	_, err := q.db.Exec(ctx, insertCommand,
		arg.TenantID,
		arg.CommandID,
		arg.OperationID,
		arg.ActorID,
		arg.Kind,
		arg.ExpectedRevision,
		arg.RequestDigest,
		arg.TargetDefinitionActivation,
		arg.Outcome,
		arg.ReasonCode,
		arg.OperationRevision,
		arg.AcceptedAt,
		arg.SettledAt,
		arg.RelayState,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO operations (
    operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision,
    semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq,
    execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at,
    definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $27, $28,
    $29, $30, $31, $32, $33
)
`

type InsertOperationParams struct {
	OperationID          string
	TenantID             string
	ProjectID            string
	ActorID              string
	CommandID            string
	Kind                 string
	ProfileID            string
	SubjectDigest        string
	BriefID              *string
	SourceRevision       *string
	SemanticDigest       string
	Lifecycle            string
	Phase                string
	ControlState         string
	CleanupState         string
	FinanceState         string
	FailureCode          *string
	Revision             int64
	NextEventSeq         int64
	ExecutionEpoch       int64
	RecoveryEpoch        int64
	Deadline             pgtype.Timestamptz
	IntakeState          string
	IntakeVersion        *string
	RelayState           string
	RelayRunID           *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DefinitionActivation string
	PromptTransferID     *string
	PromptDigest         *string
	BrandReferences      []byte
	AssetReferences      []byte
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.OperationID,
		arg.TenantID,
		arg.ProjectID,
		arg.ActorID,
		arg.CommandID,
		arg.Kind,
		arg.ProfileID,
		arg.SubjectDigest,
		arg.BriefID,
		arg.SourceRevision,
		arg.SemanticDigest,
		arg.Lifecycle,
		arg.Phase,
		arg.ControlState,
		arg.CleanupState,
		arg.FinanceState,
		arg.FailureCode,
		arg.Revision,
		arg.NextEventSeq,
		arg.ExecutionEpoch,
		arg.RecoveryEpoch,
		arg.Deadline,
		arg.IntakeState,
		arg.IntakeVersion,
		arg.RelayState,
		arg.RelayRunID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DefinitionActivation,
		arg.PromptTransferID,
		arg.PromptDigest,
		arg.BrandReferences,
		arg.AssetReferences,
	)
	return err
}

const insertOperationEvent = `-- name: InsertOperationEvent :exec
INSERT INTO operation_events (operation_id, event_seq, transition_id, event_type, revision, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOperationEventParams struct {
	OperationID  string
	EventSeq     int64
	TransitionID string
	EventType    string
	Revision     int64
	Payload      []byte
	OccurredAt   pgtype.Timestamptz
}

func (q *Queries) InsertOperationEvent(ctx context.Context, arg InsertOperationEventParams) error {
	_, err := q.db.Exec(ctx, insertOperationEvent,
		arg.OperationID,
		arg.EventSeq,
		arg.TransitionID,
		arg.EventType,
		arg.Revision,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listCommandRelayPending = `-- name: ListCommandRelayPending :many
SELECT tenant_id, command_id, operation_id, actor_id, kind, expected_revision, request_digest, target_definition_activation, outcome, reason_code, operation_revision, accepted_at, settled_at, relay_state FROM operation_commands WHERE relay_state IN ('pending', 'sent') ORDER BY accepted_at LIMIT $1
`

func (q *Queries) ListCommandRelayPending(ctx context.Context, limit int32) ([]OperationCommand, error) {
	rows, err := q.db.Query(ctx, listCommandRelayPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationCommand{}
	for rows.Next() {
		var i OperationCommand
		if err := rows.Scan(
			&i.TenantID,
			&i.CommandID,
			&i.OperationID,
			&i.ActorID,
			&i.Kind,
			&i.ExpectedRevision,
			&i.RequestDigest,
			&i.TargetDefinitionActivation,
			&i.Outcome,
			&i.ReasonCode,
			&i.OperationRevision,
			&i.AcceptedAt,
			&i.SettledAt,
			&i.RelayState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntakePending = `-- name: ListIntakePending :many
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at, active_deadline, lease_state, lease_id, lease_fence, lease_expires_at, lease_occurrence, definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references, candidate_effect_id FROM operations WHERE intake_state = 'pending' AND created_at < $1 ORDER BY created_at LIMIT $2
`

type ListIntakePendingParams struct {
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListIntakePending(ctx context.Context, arg ListIntakePendingParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listIntakePending, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.OperationID,
			&i.TenantID,
			&i.ProjectID,
			&i.ActorID,
			&i.CommandID,
			&i.Kind,
			&i.ProfileID,
			&i.SubjectDigest,
			&i.BriefID,
			&i.SourceRevision,
			&i.SemanticDigest,
			&i.Lifecycle,
			&i.Phase,
			&i.ControlState,
			&i.CleanupState,
			&i.FinanceState,
			&i.FailureCode,
			&i.Revision,
			&i.NextEventSeq,
			&i.ExecutionEpoch,
			&i.RecoveryEpoch,
			&i.Deadline,
			&i.IntakeState,
			&i.IntakeVersion,
			&i.RelayState,
			&i.RelayRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveDeadline,
			&i.LeaseState,
			&i.LeaseID,
			&i.LeaseFence,
			&i.LeaseExpiresAt,
			&i.LeaseOccurrence,
			&i.DefinitionActivation,
			&i.PromptTransferID,
			&i.PromptDigest,
			&i.BrandReferences,
			&i.AssetReferences,
			&i.CandidateEffectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationCommands = `-- name: ListOperationCommands :many
SELECT tenant_id, command_id, operation_id, actor_id, kind, expected_revision, request_digest, target_definition_activation, outcome, reason_code, operation_revision, accepted_at, settled_at, relay_state FROM operation_commands WHERE operation_id = $1 ORDER BY accepted_at
`

func (q *Queries) ListOperationCommands(ctx context.Context, operationID string) ([]OperationCommand, error) {
	rows, err := q.db.Query(ctx, listOperationCommands, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationCommand{}
	for rows.Next() {
		var i OperationCommand
		if err := rows.Scan(
			&i.TenantID,
			&i.CommandID,
			&i.OperationID,
			&i.ActorID,
			&i.Kind,
			&i.ExpectedRevision,
			&i.RequestDigest,
			&i.TargetDefinitionActivation,
			&i.Outcome,
			&i.ReasonCode,
			&i.OperationRevision,
			&i.AcceptedAt,
			&i.SettledAt,
			&i.RelayState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationEvents = `-- name: ListOperationEvents :many
SELECT operation_id, event_seq, transition_id, event_type, revision, payload, occurred_at FROM operation_events WHERE operation_id = $1 AND event_seq > $2 ORDER BY event_seq LIMIT $3
`

type ListOperationEventsParams struct {
	OperationID string
	EventSeq    int64
	Limit       int32
}

func (q *Queries) ListOperationEvents(ctx context.Context, arg ListOperationEventsParams) ([]OperationEvent, error) {
	rows, err := q.db.Query(ctx, listOperationEvents, arg.OperationID, arg.EventSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationEvent{}
	for rows.Next() {
		var i OperationEvent
		if err := rows.Scan(
			&i.OperationID,
			&i.EventSeq,
			&i.TransitionID,
			&i.EventType,
			&i.Revision,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelayPending = `-- name: ListRelayPending :many
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at, active_deadline, lease_state, lease_id, lease_fence, lease_expires_at, lease_occurrence, definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references, candidate_effect_id FROM operations
WHERE (relay_state = 'pending' AND intake_state = 'confirmed') OR relay_state = 'cancel_pending'
ORDER BY created_at LIMIT $1
`

func (q *Queries) ListRelayPending(ctx context.Context, limit int32) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listRelayPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.OperationID,
			&i.TenantID,
			&i.ProjectID,
			&i.ActorID,
			&i.CommandID,
			&i.Kind,
			&i.ProfileID,
			&i.SubjectDigest,
			&i.BriefID,
			&i.SourceRevision,
			&i.SemanticDigest,
			&i.Lifecycle,
			&i.Phase,
			&i.ControlState,
			&i.CleanupState,
			&i.FinanceState,
			&i.FailureCode,
			&i.Revision,
			&i.NextEventSeq,
			&i.ExecutionEpoch,
			&i.RecoveryEpoch,
			&i.Deadline,
			&i.IntakeState,
			&i.IntakeVersion,
			&i.RelayState,
			&i.RelayRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveDeadline,
			&i.LeaseState,
			&i.LeaseID,
			&i.LeaseFence,
			&i.LeaseExpiresAt,
			&i.LeaseOccurrence,
			&i.DefinitionActivation,
			&i.PromptTransferID,
			&i.PromptDigest,
			&i.BrandReferences,
			&i.AssetReferences,
			&i.CandidateEffectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCommand = `-- name: LockCommand :one
SELECT tenant_id, command_id, operation_id, actor_id, kind, expected_revision, request_digest, target_definition_activation, outcome, reason_code, operation_revision, accepted_at, settled_at, relay_state FROM operation_commands WHERE tenant_id = $1 AND command_id = $2 FOR UPDATE
`

type LockCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) LockCommand(ctx context.Context, arg LockCommandParams) (OperationCommand, error) {
	row := q.db.QueryRow(ctx, lockCommand, arg.TenantID, arg.CommandID)
	var i OperationCommand
	err := row.Scan(
		&i.TenantID,
		&i.CommandID,
		&i.OperationID,
		&i.ActorID,
		&i.Kind,
		&i.ExpectedRevision,
		&i.RequestDigest,
		&i.TargetDefinitionActivation,
		&i.Outcome,
		&i.ReasonCode,
		&i.OperationRevision,
		&i.AcceptedAt,
		&i.SettledAt,
		&i.RelayState,
	)
	return i, err
}

const lockOperation = `-- name: LockOperation :one
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at, active_deadline, lease_state, lease_id, lease_fence, lease_expires_at, lease_occurrence, definition_activation, prompt_transfer_id, prompt_digest, brand_references, asset_references, candidate_effect_id FROM operations WHERE operation_id = $1 FOR UPDATE
`

func (q *Queries) LockOperation(ctx context.Context, operationID string) (Operation, error) {
	row := q.db.QueryRow(ctx, lockOperation, operationID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.ProjectID,
		&i.ActorID,
		&i.CommandID,
		&i.Kind,
		&i.ProfileID,
		&i.SubjectDigest,
		&i.BriefID,
		&i.SourceRevision,
		&i.SemanticDigest,
		&i.Lifecycle,
		&i.Phase,
		&i.ControlState,
		&i.CleanupState,
		&i.FinanceState,
		&i.FailureCode,
		&i.Revision,
		&i.NextEventSeq,
		&i.ExecutionEpoch,
		&i.RecoveryEpoch,
		&i.Deadline,
		&i.IntakeState,
		&i.IntakeVersion,
		&i.RelayState,
		&i.RelayRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveDeadline,
		&i.LeaseState,
		&i.LeaseID,
		&i.LeaseFence,
		&i.LeaseExpiresAt,
		&i.LeaseOccurrence,
		&i.DefinitionActivation,
		&i.PromptTransferID,
		&i.PromptDigest,
		&i.BrandReferences,
		&i.AssetReferences,
		&i.CandidateEffectID,
	)
	return i, err
}

const settlePendingCommands = `-- name: SettlePendingCommands :exec
UPDATE operation_commands SET outcome = $3, operation_revision = $4, settled_at = $5
WHERE operation_id = $1 AND kind = $2 AND outcome = 'pending'
`

type SettlePendingCommandsParams struct {
	OperationID       string
	Kind              string
	Outcome           string
	OperationRevision int64
	SettledAt         pgtype.Timestamptz
}

func (q *Queries) SettlePendingCommands(ctx context.Context, arg SettlePendingCommandsParams) error {
	_, err := q.db.Exec(ctx, settlePendingCommands,
		arg.OperationID,
		arg.Kind,
		arg.Outcome,
		arg.OperationRevision,
		arg.SettledAt,
	)
	return err
}

const updateCommand = `-- name: UpdateCommand :exec
UPDATE operation_commands SET outcome = $3, reason_code = $4, operation_revision = $5, settled_at = $6, relay_state = $7
WHERE tenant_id = $1 AND command_id = $2
`

type UpdateCommandParams struct {
	TenantID          string
	CommandID         string
	Outcome           string
	ReasonCode        *string
	OperationRevision int64
	SettledAt         pgtype.Timestamptz
	RelayState        string
}

func (q *Queries) UpdateCommand(ctx context.Context, arg UpdateCommandParams) error {
	_, err := q.db.Exec(ctx, updateCommand,
		arg.TenantID,
		arg.CommandID,
		arg.Outcome,
		arg.ReasonCode,
		arg.OperationRevision,
		arg.SettledAt,
		arg.RelayState,
	)
	return err
}

const updateOperation = `-- name: UpdateOperation :exec
UPDATE operations SET
    lifecycle = $2, phase = $3, control_state = $4, cleanup_state = $5, finance_state = $6, failure_code = $7,
    revision = $8, next_event_seq = $9, execution_epoch = $10, recovery_epoch = $11,
    intake_state = $12, intake_version = $13, relay_state = $14, relay_run_id = $15, updated_at = $16,
    active_deadline = $17, lease_state = $18, lease_id = $19, lease_fence = $20, lease_expires_at = $21, lease_occurrence = $22,
    definition_activation = $23, brief_id = $24, candidate_effect_id = $25
WHERE operation_id = $1
`

type UpdateOperationParams struct {
	OperationID          string
	Lifecycle            string
	Phase                string
	ControlState         string
	CleanupState         string
	FinanceState         string
	FailureCode          *string
	Revision             int64
	NextEventSeq         int64
	ExecutionEpoch       int64
	RecoveryEpoch        int64
	IntakeState          string
	IntakeVersion        *string
	RelayState           string
	RelayRunID           *string
	UpdatedAt            pgtype.Timestamptz
	ActiveDeadline       pgtype.Timestamptz
	LeaseState           string
	LeaseID              *string
	LeaseFence           *int64
	LeaseExpiresAt       pgtype.Timestamptz
	LeaseOccurrence      int64
	DefinitionActivation string
	BriefID              *string
	CandidateEffectID    *string
}

func (q *Queries) UpdateOperation(ctx context.Context, arg UpdateOperationParams) error {
	_, err := q.db.Exec(ctx, updateOperation,
		arg.OperationID,
		arg.Lifecycle,
		arg.Phase,
		arg.ControlState,
		arg.CleanupState,
		arg.FinanceState,
		arg.FailureCode,
		arg.Revision,
		arg.NextEventSeq,
		arg.ExecutionEpoch,
		arg.RecoveryEpoch,
		arg.IntakeState,
		arg.IntakeVersion,
		arg.RelayState,
		arg.RelayRunID,
		arg.UpdatedAt,
		arg.ActiveDeadline,
		arg.LeaseState,
		arg.LeaseID,
		arg.LeaseFence,
		arg.LeaseExpiresAt,
		arg.LeaseOccurrence,
		arg.DefinitionActivation,
		arg.BriefID,
		arg.CandidateEffectID,
	)
	return err
}
