// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: preparation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBriefs = `-- name: CountBriefs :one
SELECT count(*) FROM briefs WHERE operation_id = $1
`

func (q *Queries) CountBriefs(ctx context.Context, operationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBriefs, operationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnswer = `-- name: GetAnswer :one
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE answer_id = $1
`

func (q *Queries) GetAnswer(ctx context.Context, answerID string) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, answerID)
	var i Answer
	err := row.Scan(
		&i.AnswerID,
		&i.OperationID,
		&i.TenantID,
		&i.ActorID,
		&i.QuestionSetID,
		&i.QuestionSetRevision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.UpdateID,
		&i.CommandID,
		&i.RequestDigest,
		&i.RelayState,
		&i.AcceptedAt,
		&i.RelayedAt,
	)
	return i, err
}

const getAnswerByCommand = `-- name: GetAnswerByCommand :one
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE tenant_id = $1 AND command_id = $2
`

type GetAnswerByCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) GetAnswerByCommand(ctx context.Context, arg GetAnswerByCommandParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByCommand, arg.TenantID, arg.CommandID)
	var i Answer
	err := row.Scan(
		&i.AnswerID,
		&i.OperationID,
		&i.TenantID,
		&i.ActorID,
		&i.QuestionSetID,
		&i.QuestionSetRevision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.UpdateID,
		&i.CommandID,
		&i.RequestDigest,
		&i.RelayState,
		&i.AcceptedAt,
		&i.RelayedAt,
	)
	return i, err
}

const getAnswerByQuestionSet = `-- name: GetAnswerByQuestionSet :one
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE question_set_id = $1 AND question_set_revision = $2
`

type GetAnswerByQuestionSetParams struct {
	QuestionSetID       string
	QuestionSetRevision int64
}

func (q *Queries) GetAnswerByQuestionSet(ctx context.Context, arg GetAnswerByQuestionSetParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswerByQuestionSet, arg.QuestionSetID, arg.QuestionSetRevision)
	var i Answer
	err := row.Scan(
		&i.AnswerID,
		&i.OperationID,
		&i.TenantID,
		&i.ActorID,
		&i.QuestionSetID,
		&i.QuestionSetRevision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.UpdateID,
		&i.CommandID,
		&i.RequestDigest,
		&i.RelayState,
		&i.AcceptedAt,
		&i.RelayedAt,
	)
	return i, err
}

const getBrief = `-- name: GetBrief :one
SELECT brief_id, operation_id, tenant_id, revision, transfer_id, digest, handle, requirements_digest, source_revisions, brand_digests, asset_digests, state, command_id, request_digest, frozen_at FROM briefs WHERE brief_id = $1
`

func (q *Queries) GetBrief(ctx context.Context, briefID string) (Brief, error) {
	row := q.db.QueryRow(ctx, getBrief, briefID)
	var i Brief
	err := row.Scan(
		&i.BriefID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.RequirementsDigest,
		&i.SourceRevisions,
		&i.BrandDigests,
		&i.AssetDigests,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.FrozenAt,
	)
	return i, err
}

const getBriefByCommand = `-- name: GetBriefByCommand :one
SELECT brief_id, operation_id, tenant_id, revision, transfer_id, digest, handle, requirements_digest, source_revisions, brand_digests, asset_digests, state, command_id, request_digest, frozen_at FROM briefs WHERE operation_id = $1 AND command_id = $2
`

type GetBriefByCommandParams struct {
	OperationID string
	CommandID   string
}

func (q *Queries) GetBriefByCommand(ctx context.Context, arg GetBriefByCommandParams) (Brief, error) {
	row := q.db.QueryRow(ctx, getBriefByCommand, arg.OperationID, arg.CommandID)
	var i Brief
	err := row.Scan(
		&i.BriefID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.RequirementsDigest,
		&i.SourceRevisions,
		&i.BrandDigests,
		&i.AssetDigests,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.FrozenAt,
	)
	return i, err
}

const getCurrentBrief = `-- name: GetCurrentBrief :one
SELECT brief_id, operation_id, tenant_id, revision, transfer_id, digest, handle, requirements_digest, source_revisions, brand_digests, asset_digests, state, command_id, request_digest, frozen_at FROM briefs WHERE operation_id = $1 AND state = 'current'
`

func (q *Queries) GetCurrentBrief(ctx context.Context, operationID string) (Brief, error) {
	row := q.db.QueryRow(ctx, getCurrentBrief, operationID)
	var i Brief
	err := row.Scan(
		&i.BriefID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.RequirementsDigest,
		&i.SourceRevisions,
		&i.BrandDigests,
		&i.AssetDigests,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.FrozenAt,
	)
	return i, err
}

const getOpenQuestionSet = `-- name: GetOpenQuestionSet :one
SELECT question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at FROM question_sets WHERE operation_id = $1 AND state = 'open'
`

func (q *Queries) GetOpenQuestionSet(ctx context.Context, operationID string) (QuestionSet, error) {
	row := q.db.QueryRow(ctx, getOpenQuestionSet, operationID)
	var i QuestionSet
	err := row.Scan(
		&i.QuestionSetID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.Round,
		&i.Questions,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.AskedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getQuestionSet = `-- name: GetQuestionSet :one
SELECT question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at FROM question_sets WHERE question_set_id = $1
`

func (q *Queries) GetQuestionSet(ctx context.Context, questionSetID string) (QuestionSet, error) {
	row := q.db.QueryRow(ctx, getQuestionSet, questionSetID)
	var i QuestionSet
	err := row.Scan(
		&i.QuestionSetID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.Round,
		&i.Questions,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.AskedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getQuestionSetByCommand = `-- name: GetQuestionSetByCommand :one
SELECT question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at FROM question_sets WHERE operation_id = $1 AND command_id = $2
`

type GetQuestionSetByCommandParams struct {
	OperationID string
	CommandID   string
}

func (q *Queries) GetQuestionSetByCommand(ctx context.Context, arg GetQuestionSetByCommandParams) (QuestionSet, error) {
	row := q.db.QueryRow(ctx, getQuestionSetByCommand, arg.OperationID, arg.CommandID)
	var i QuestionSet
	err := row.Scan(
		&i.QuestionSetID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.Round,
		&i.Questions,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.AskedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO answers (
    answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id,
    command_id, request_digest, relay_state, accepted_at, relayed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertAnswerParams struct {
	AnswerID            string
	OperationID         string
	TenantID            string
	ActorID             string
	QuestionSetID       string
	QuestionSetRevision int64
	TransferID          string
	Digest              string
	Handle              string
	UpdateID            string
	CommandID           string
	RequestDigest       string
	RelayState          string
	AcceptedAt          pgtype.Timestamptz
	RelayedAt           pgtype.Timestamptz
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAnswer,
		arg.AnswerID,
		arg.OperationID,
		arg.TenantID,
		arg.ActorID,
		arg.QuestionSetID,
		arg.QuestionSetRevision,
		arg.TransferID,
		arg.Digest,
		arg.Handle,
		arg.UpdateID,
		arg.CommandID,
		arg.RequestDigest,
		arg.RelayState,
		arg.AcceptedAt,
		arg.RelayedAt,
	)
	return err
}

const insertBrief = `-- name: InsertBrief :exec
INSERT INTO briefs (
    brief_id, operation_id, tenant_id, revision, transfer_id, digest, handle, requirements_digest, source_revisions, brand_digests,
    asset_digests, state, command_id, request_digest, frozen_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertBriefParams struct {
	BriefID            string
	OperationID        string
	TenantID           string
	Revision           int64
	TransferID         string
	Digest             string
	Handle             string
	RequirementsDigest string
	SourceRevisions    []byte
	BrandDigests       []byte
	AssetDigests       []byte
	State              string
	CommandID          string
	RequestDigest      string
	FrozenAt           pgtype.Timestamptz
}

func (q *Queries) InsertBrief(ctx context.Context, arg InsertBriefParams) error {
	_, err := q.db.Exec(ctx, insertBrief,
		arg.BriefID,
		arg.OperationID,
		arg.TenantID,
		arg.Revision,
		arg.TransferID,
		arg.Digest,
		arg.Handle,
		arg.RequirementsDigest,
		arg.SourceRevisions,
		arg.BrandDigests,
		arg.AssetDigests,
		arg.State,
		arg.CommandID,
		arg.RequestDigest,
		arg.FrozenAt,
	)
	return err
}

const insertQuestionSet = `-- name: InsertQuestionSet :exec
INSERT INTO question_sets (
    question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertQuestionSetParams struct {
	QuestionSetID string
	OperationID   string
	TenantID      string
	Revision      int64
	Round         int64
	Questions     []byte
	State         string
	CommandID     string
	RequestDigest string
	AskedAt       pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) InsertQuestionSet(ctx context.Context, arg InsertQuestionSetParams) error {
	_, err := q.db.Exec(ctx, insertQuestionSet,
		arg.QuestionSetID,
		arg.OperationID,
		arg.TenantID,
		arg.Revision,
		arg.Round,
		arg.Questions,
		arg.State,
		arg.CommandID,
		arg.RequestDigest,
		arg.AskedAt,
		arg.ExpiresAt,
	)
	return err
}

const listAnswerRelayPending = `-- name: ListAnswerRelayPending :many
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE relay_state IN ('pending', 'sent') ORDER BY accepted_at LIMIT $1
`

func (q *Queries) ListAnswerRelayPending(ctx context.Context, limit int32) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswerRelayPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.AnswerID,
			&i.OperationID,
			&i.TenantID,
			&i.ActorID,
			&i.QuestionSetID,
			&i.QuestionSetRevision,
			&i.TransferID,
			&i.Digest,
			&i.Handle,
			&i.UpdateID,
			&i.CommandID,
			&i.RequestDigest,
			&i.RelayState,
			&i.AcceptedAt,
			&i.RelayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswers = `-- name: ListAnswers :many
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE operation_id = $1 ORDER BY accepted_at
`

func (q *Queries) ListAnswers(ctx context.Context, operationID string) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswers, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.AnswerID,
			&i.OperationID,
			&i.TenantID,
			&i.ActorID,
			&i.QuestionSetID,
			&i.QuestionSetRevision,
			&i.TransferID,
			&i.Digest,
			&i.Handle,
			&i.UpdateID,
			&i.CommandID,
			&i.RequestDigest,
			&i.RelayState,
			&i.AcceptedAt,
			&i.RelayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionSets = `-- name: ListQuestionSets :many
SELECT question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at FROM question_sets WHERE operation_id = $1 ORDER BY round
`

func (q *Queries) ListQuestionSets(ctx context.Context, operationID string) ([]QuestionSet, error) {
	rows, err := q.db.Query(ctx, listQuestionSets, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionSet{}
	for rows.Next() {
		var i QuestionSet
		if err := rows.Scan(
			&i.QuestionSetID,
			&i.OperationID,
			&i.TenantID,
			&i.Revision,
			&i.Round,
			&i.Questions,
			&i.State,
			&i.CommandID,
			&i.RequestDigest,
			&i.AskedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAnswer = `-- name: LockAnswer :one
SELECT answer_id, operation_id, tenant_id, actor_id, question_set_id, question_set_revision, transfer_id, digest, handle, update_id, command_id, request_digest, relay_state, accepted_at, relayed_at FROM answers WHERE answer_id = $1 FOR UPDATE
`

func (q *Queries) LockAnswer(ctx context.Context, answerID string) (Answer, error) {
	row := q.db.QueryRow(ctx, lockAnswer, answerID)
	var i Answer
	err := row.Scan(
		&i.AnswerID,
		&i.OperationID,
		&i.TenantID,
		&i.ActorID,
		&i.QuestionSetID,
		&i.QuestionSetRevision,
		&i.TransferID,
		&i.Digest,
		&i.Handle,
		&i.UpdateID,
		&i.CommandID,
		&i.RequestDigest,
		&i.RelayState,
		&i.AcceptedAt,
		&i.RelayedAt,
	)
	return i, err
}

const lockQuestionSet = `-- name: LockQuestionSet :one
SELECT question_set_id, operation_id, tenant_id, revision, round, questions, state, command_id, request_digest, asked_at, expires_at FROM question_sets WHERE question_set_id = $1 FOR UPDATE
`

func (q *Queries) LockQuestionSet(ctx context.Context, questionSetID string) (QuestionSet, error) {
	row := q.db.QueryRow(ctx, lockQuestionSet, questionSetID)
	var i QuestionSet
	err := row.Scan(
		&i.QuestionSetID,
		&i.OperationID,
		&i.TenantID,
		&i.Revision,
		&i.Round,
		&i.Questions,
		&i.State,
		&i.CommandID,
		&i.RequestDigest,
		&i.AskedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const supersedeBriefs = `-- name: SupersedeBriefs :exec
UPDATE briefs SET state = 'superseded' WHERE operation_id = $1 AND state = 'current'
`

func (q *Queries) SupersedeBriefs(ctx context.Context, operationID string) error {
	_, err := q.db.Exec(ctx, supersedeBriefs, operationID)
	return err
}

const updateAnswerRelay = `-- name: UpdateAnswerRelay :exec
UPDATE answers SET relay_state = $2, relayed_at = $3 WHERE answer_id = $1
`

type UpdateAnswerRelayParams struct {
	AnswerID   string
	RelayState string
	RelayedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateAnswerRelay(ctx context.Context, arg UpdateAnswerRelayParams) error {
	_, err := q.db.Exec(ctx, updateAnswerRelay, arg.AnswerID, arg.RelayState, arg.RelayedAt)
	return err
}

const updateQuestionSetState = `-- name: UpdateQuestionSetState :exec
UPDATE question_sets SET state = $2 WHERE question_set_id = $1
`

type UpdateQuestionSetStateParams struct {
	QuestionSetID string
	State         string
}

func (q *Queries) UpdateQuestionSetState(ctx context.Context, arg UpdateQuestionSetStateParams) error {
	_, err := q.db.Exec(ctx, updateQuestionSetState, arg.QuestionSetID, arg.State)
	return err
}
