// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: previews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCertifiedSourceArtifact = `-- name: GetCertifiedSourceArtifact :one
SELECT sa.stage_id, sa.transfer_id, sa.handle, sa.class, sa.digest, sa.size_bytes, sa.object_version FROM stage_artifacts sa JOIN stage_manifests sm ON sm.stage_id = sa.stage_id
WHERE sm.operation_id = $1 AND sa.class = 'source' AND sm.verdict = 'certified'
ORDER BY sm.accepted_at DESC LIMIT 1
`

func (q *Queries) GetCertifiedSourceArtifact(ctx context.Context, operationID string) (StageArtifact, error) {
	row := q.db.QueryRow(ctx, getCertifiedSourceArtifact, operationID)
	var i StageArtifact
	err := row.Scan(
		&i.StageID,
		&i.TransferID,
		&i.Handle,
		&i.Class,
		&i.Digest,
		&i.SizeBytes,
		&i.ObjectVersion,
	)
	return i, err
}

const getPreview = `-- name: GetPreview :one

SELECT operation_id, tenant_id, subject_digest, base_revision, state, source_revision, current_revision, source_digest, module, styles, build_profile_id, host_profile_id, failure_code, revision, updated_at FROM previews WHERE operation_id = $1
`

// Preview builds (P20): the committed projection of a preview_build
// operation, changed only under its expected revision.
func (q *Queries) GetPreview(ctx context.Context, operationID string) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreview, operationID)
	var i Preview
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.SubjectDigest,
		&i.BaseRevision,
		&i.State,
		&i.SourceRevision,
		&i.CurrentRevision,
		&i.SourceDigest,
		&i.Module,
		&i.Styles,
		&i.BuildProfileID,
		&i.HostProfileID,
		&i.FailureCode,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPreview = `-- name: InsertPreview :exec
INSERT INTO previews (operation_id, tenant_id, subject_digest, base_revision, state, source_revision, current_revision, source_digest,
    module, styles, build_profile_id, host_profile_id, failure_code, revision, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertPreviewParams struct {
	OperationID     string
	TenantID        string
	SubjectDigest   string
	BaseRevision    string
	State           string
	SourceRevision  *string
	CurrentRevision *string
	SourceDigest    string
	Module          []byte
	Styles          []byte
	BuildProfileID  string
	HostProfileID   string
	FailureCode     *string
	Revision        int64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertPreview(ctx context.Context, arg InsertPreviewParams) error {
	_, err := q.db.Exec(ctx, insertPreview,
		arg.OperationID,
		arg.TenantID,
		arg.SubjectDigest,
		arg.BaseRevision,
		arg.State,
		arg.SourceRevision,
		arg.CurrentRevision,
		arg.SourceDigest,
		arg.Module,
		arg.Styles,
		arg.BuildProfileID,
		arg.HostProfileID,
		arg.FailureCode,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}

const lockPreview = `-- name: LockPreview :one
SELECT operation_id, tenant_id, subject_digest, base_revision, state, source_revision, current_revision, source_digest, module, styles, build_profile_id, host_profile_id, failure_code, revision, updated_at FROM previews WHERE operation_id = $1 FOR UPDATE
`

func (q *Queries) LockPreview(ctx context.Context, operationID string) (Preview, error) {
	row := q.db.QueryRow(ctx, lockPreview, operationID)
	var i Preview
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.SubjectDigest,
		&i.BaseRevision,
		&i.State,
		&i.SourceRevision,
		&i.CurrentRevision,
		&i.SourceDigest,
		&i.Module,
		&i.Styles,
		&i.BuildProfileID,
		&i.HostProfileID,
		&i.FailureCode,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreview = `-- name: UpdatePreview :execrows
UPDATE previews SET state = $2, source_revision = $3, current_revision = $4, source_digest = $5, module = $6, styles = $7,
    build_profile_id = $8, host_profile_id = $9, failure_code = $10, revision = $11, updated_at = $12
WHERE operation_id = $1 AND revision = $13
`

type UpdatePreviewParams struct {
	OperationID      string
	State            string
	SourceRevision   *string
	CurrentRevision  *string
	SourceDigest     string
	Module           []byte
	Styles           []byte
	BuildProfileID   string
	HostProfileID    string
	FailureCode      *string
	Revision         int64
	UpdatedAt        pgtype.Timestamptz
	ExpectedRevision int64
}

func (q *Queries) UpdatePreview(ctx context.Context, arg UpdatePreviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePreview,
		arg.OperationID,
		arg.State,
		arg.SourceRevision,
		arg.CurrentRevision,
		arg.SourceDigest,
		arg.Module,
		arg.Styles,
		arg.BuildProfileID,
		arg.HostProfileID,
		arg.FailureCode,
		arg.Revision,
		arg.UpdatedAt,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
