// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recovery.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnsettledFindings = `-- name: CountUnsettledFindings :one
SELECT count(*) FROM recovery_findings WHERE run_id = $1 AND status NOT IN ('present', 'resolved', 'disposed', 'outside_scope')
`

func (q *Queries) CountUnsettledFindings(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsettledFindings, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdmissionClosure = `-- name: GetAdmissionClosure :one
SELECT scope_key, run_id, closed_at, reopened_at FROM admission_closures WHERE scope_key = $1
`

func (q *Queries) GetAdmissionClosure(ctx context.Context, scopeKey string) (AdmissionClosure, error) {
	row := q.db.QueryRow(ctx, getAdmissionClosure, scopeKey)
	var i AdmissionClosure
	err := row.Scan(
		&i.ScopeKey,
		&i.RunID,
		&i.ClosedAt,
		&i.ReopenedAt,
	)
	return i, err
}

const getFinding = `-- name: GetFinding :one
SELECT finding_id, run_id, class, obligation_id, tenant_id, inventory_key, inventory_version, recorded_at, status, outcome, evidence_ref, detail, created_at, updated_at FROM recovery_findings WHERE finding_id = $1
`

func (q *Queries) GetFinding(ctx context.Context, findingID string) (RecoveryFinding, error) {
	row := q.db.QueryRow(ctx, getFinding, findingID)
	var i RecoveryFinding
	err := row.Scan(
		&i.FindingID,
		&i.RunID,
		&i.Class,
		&i.ObligationID,
		&i.TenantID,
		&i.InventoryKey,
		&i.InventoryVersion,
		&i.RecordedAt,
		&i.Status,
		&i.Outcome,
		&i.EvidenceRef,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingByObligation = `-- name: GetFindingByObligation :one
SELECT finding_id, run_id, class, obligation_id, tenant_id, inventory_key, inventory_version, recorded_at, status, outcome, evidence_ref, detail, created_at, updated_at FROM recovery_findings WHERE run_id = $1 AND class = $2 AND obligation_id = $3
`

type GetFindingByObligationParams struct {
	RunID        string
	Class        string
	ObligationID string
}

func (q *Queries) GetFindingByObligation(ctx context.Context, arg GetFindingByObligationParams) (RecoveryFinding, error) {
	row := q.db.QueryRow(ctx, getFindingByObligation, arg.RunID, arg.Class, arg.ObligationID)
	var i RecoveryFinding
	err := row.Scan(
		&i.FindingID,
		&i.RunID,
		&i.Class,
		&i.ObligationID,
		&i.TenantID,
		&i.InventoryKey,
		&i.InventoryVersion,
		&i.RecordedAt,
		&i.Status,
		&i.Outcome,
		&i.EvidenceRef,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryProgress = `-- name: GetRecoveryProgress :one
SELECT run_id, class, cursor, complete, seen FROM recovery_progress WHERE run_id = $1 AND class = $2
`

type GetRecoveryProgressParams struct {
	RunID string
	Class string
}

func (q *Queries) GetRecoveryProgress(ctx context.Context, arg GetRecoveryProgressParams) (RecoveryProgress, error) {
	row := q.db.QueryRow(ctx, getRecoveryProgress, arg.RunID, arg.Class)
	var i RecoveryProgress
	err := row.Scan(
		&i.RunID,
		&i.Class,
		&i.Cursor,
		&i.Complete,
		&i.Seen,
	)
	return i, err
}

const getRecoveryRun = `-- name: GetRecoveryRun :one
SELECT run_id, scope_key, tenant_id, command_id, actor_id, request_digest, recovery_epoch, phase, window_start, window_end, skew_micros, reason, fenced_count, created_at, updated_at, reopened_at FROM recovery_runs WHERE run_id = $1
`

func (q *Queries) GetRecoveryRun(ctx context.Context, runID string) (RecoveryRun, error) {
	row := q.db.QueryRow(ctx, getRecoveryRun, runID)
	var i RecoveryRun
	err := row.Scan(
		&i.RunID,
		&i.ScopeKey,
		&i.TenantID,
		&i.CommandID,
		&i.ActorID,
		&i.RequestDigest,
		&i.RecoveryEpoch,
		&i.Phase,
		&i.WindowStart,
		&i.WindowEnd,
		&i.SkewMicros,
		&i.Reason,
		&i.FencedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReopenedAt,
	)
	return i, err
}

const getRecoveryRunByCommand = `-- name: GetRecoveryRunByCommand :one

SELECT run_id, scope_key, tenant_id, command_id, actor_id, request_digest, recovery_epoch, phase, window_start, window_end, skew_micros, reason, fenced_count, created_at, updated_at, reopened_at FROM recovery_runs WHERE scope_key = $1 AND command_id = $2
`

type GetRecoveryRunByCommandParams struct {
	ScopeKey  string
	CommandID string
}

// Recovery runs over a rollback window, their resumable enumeration
// cursors, findings and the admission closure of a scope (DD-02 §5,
// platform.md recovery gates, P07). The run row is locked (rank 1, before
// any operation) for every phase change.
func (q *Queries) GetRecoveryRunByCommand(ctx context.Context, arg GetRecoveryRunByCommandParams) (RecoveryRun, error) {
	row := q.db.QueryRow(ctx, getRecoveryRunByCommand, arg.ScopeKey, arg.CommandID)
	var i RecoveryRun
	err := row.Scan(
		&i.RunID,
		&i.ScopeKey,
		&i.TenantID,
		&i.CommandID,
		&i.ActorID,
		&i.RequestDigest,
		&i.RecoveryEpoch,
		&i.Phase,
		&i.WindowStart,
		&i.WindowEnd,
		&i.SkewMicros,
		&i.Reason,
		&i.FencedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReopenedAt,
	)
	return i, err
}

const hasOpenRecoveryFor = `-- name: HasOpenRecoveryFor :one
SELECT EXISTS (SELECT 1 FROM admission_closures WHERE scope_key = $1 AND reopened_at IS NULL)
`

func (q *Queries) HasOpenRecoveryFor(ctx context.Context, scopeKey string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenRecoveryFor, scopeKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertFinding = `-- name: InsertFinding :exec
INSERT INTO recovery_findings (
    finding_id, run_id, class, obligation_id, tenant_id, inventory_key, inventory_version, recorded_at, status, outcome, evidence_ref, detail, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertFindingParams struct {
	FindingID        string
	RunID            string
	Class            string
	ObligationID     string
	TenantID         string
	InventoryKey     string
	InventoryVersion string
	RecordedAt       pgtype.Timestamptz
	Status           string
	Outcome          string
	EvidenceRef      string
	Detail           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.Exec(ctx, insertFinding,
		arg.FindingID,
		arg.RunID,
		arg.Class,
		arg.ObligationID,
		arg.TenantID,
		arg.InventoryKey,
		arg.InventoryVersion,
		arg.RecordedAt,
		arg.Status,
		arg.Outcome,
		arg.EvidenceRef,
		arg.Detail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRecoveryRun = `-- name: InsertRecoveryRun :exec
INSERT INTO recovery_runs (
    run_id, scope_key, tenant_id, command_id, actor_id, request_digest, recovery_epoch, phase, window_start, window_end,
    skew_micros, reason, fenced_count, created_at, updated_at, reopened_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertRecoveryRunParams struct {
	RunID         string
	ScopeKey      string
	TenantID      string
	CommandID     string
	ActorID       string
	RequestDigest string
	RecoveryEpoch int64
	Phase         string
	WindowStart   pgtype.Timestamptz
	WindowEnd     pgtype.Timestamptz
	SkewMicros    int64
	Reason        string
	FencedCount   int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ReopenedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRecoveryRun(ctx context.Context, arg InsertRecoveryRunParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryRun,
		arg.RunID,
		arg.ScopeKey,
		arg.TenantID,
		arg.CommandID,
		arg.ActorID,
		arg.RequestDigest,
		arg.RecoveryEpoch,
		arg.Phase,
		arg.WindowStart,
		arg.WindowEnd,
		arg.SkewMicros,
		arg.Reason,
		arg.FencedCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReopenedAt,
	)
	return err
}

const isAdmissionClosed = `-- name: IsAdmissionClosed :one
SELECT EXISTS (SELECT 1 FROM admission_closures WHERE scope_key IN ('*', $1) AND reopened_at IS NULL)
`

func (q *Queries) IsAdmissionClosed(ctx context.Context, scopeKey string) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmissionClosed, scopeKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveOperations = `-- name: ListActiveOperations :many
SELECT operation_id, tenant_id, project_id, actor_id, command_id, kind, profile_id, subject_digest, brief_id, source_revision, semantic_digest, lifecycle, phase, control_state, cleanup_state, finance_state, failure_code, revision, next_event_seq, execution_epoch, recovery_epoch, deadline, intake_state, intake_version, relay_state, relay_run_id, created_at, updated_at FROM operations
WHERE lifecycle IN ('accepted', 'running', 'waiting', 'reconciling', 'suspended') AND ($1::text = '*' OR tenant_id = $1)
ORDER BY operation_id
`

func (q *Queries) ListActiveOperations(ctx context.Context, dollar_1 string) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listActiveOperations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.OperationID,
			&i.TenantID,
			&i.ProjectID,
			&i.ActorID,
			&i.CommandID,
			&i.Kind,
			&i.ProfileID,
			&i.SubjectDigest,
			&i.BriefID,
			&i.SourceRevision,
			&i.SemanticDigest,
			&i.Lifecycle,
			&i.Phase,
			&i.ControlState,
			&i.CleanupState,
			&i.FinanceState,
			&i.FailureCode,
			&i.Revision,
			&i.NextEventSeq,
			&i.ExecutionEpoch,
			&i.RecoveryEpoch,
			&i.Deadline,
			&i.IntakeState,
			&i.IntakeVersion,
			&i.RelayState,
			&i.RelayRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindings = `-- name: ListFindings :many
SELECT finding_id, run_id, class, obligation_id, tenant_id, inventory_key, inventory_version, recorded_at, status, outcome, evidence_ref, detail, created_at, updated_at FROM recovery_findings
WHERE run_id = $1 AND ($2::text = '' OR status = $2) AND (class, obligation_id) > ($3::text, $4::text)
ORDER BY class, obligation_id LIMIT $5
`

type ListFindingsParams struct {
	RunID   string
	Column2 string
	Column3 string
	Column4 string
	Limit   int32
}

// Keyset pagination over the fixed (class, obligation_id) order: the cursor
// is the key of the last finding of the previous page, so every finding is
// reached whatever the state of the ones before it.
func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]RecoveryFinding, error) {
	rows, err := q.db.Query(ctx, listFindings,
		arg.RunID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryFinding{}
	for rows.Next() {
		var i RecoveryFinding
		if err := rows.Scan(
			&i.FindingID,
			&i.RunID,
			&i.Class,
			&i.ObligationID,
			&i.TenantID,
			&i.InventoryKey,
			&i.InventoryVersion,
			&i.RecordedAt,
			&i.Status,
			&i.Outcome,
			&i.EvidenceRef,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryPending = `-- name: ListRecoveryPending :many
SELECT run_id, scope_key, tenant_id, command_id, actor_id, request_digest, recovery_epoch, phase, window_start, window_end, skew_micros, reason, fenced_count, created_at, updated_at, reopened_at FROM recovery_runs WHERE phase = 'fenced' ORDER BY created_at LIMIT $1
`

func (q *Queries) ListRecoveryPending(ctx context.Context, limit int32) ([]RecoveryRun, error) {
	rows, err := q.db.Query(ctx, listRecoveryPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryRun{}
	for rows.Next() {
		var i RecoveryRun
		if err := rows.Scan(
			&i.RunID,
			&i.ScopeKey,
			&i.TenantID,
			&i.CommandID,
			&i.ActorID,
			&i.RequestDigest,
			&i.RecoveryEpoch,
			&i.Phase,
			&i.WindowStart,
			&i.WindowEnd,
			&i.SkewMicros,
			&i.Reason,
			&i.FencedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReopenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryProgress = `-- name: ListRecoveryProgress :many
SELECT run_id, class, cursor, complete, seen FROM recovery_progress WHERE run_id = $1 ORDER BY class
`

func (q *Queries) ListRecoveryProgress(ctx context.Context, runID string) ([]RecoveryProgress, error) {
	rows, err := q.db.Query(ctx, listRecoveryProgress, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryProgress{}
	for rows.Next() {
		var i RecoveryProgress
		if err := rows.Scan(
			&i.RunID,
			&i.Class,
			&i.Cursor,
			&i.Complete,
			&i.Seen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFinding = `-- name: LockFinding :one
SELECT finding_id, run_id, class, obligation_id, tenant_id, inventory_key, inventory_version, recorded_at, status, outcome, evidence_ref, detail, created_at, updated_at FROM recovery_findings WHERE finding_id = $1 FOR UPDATE
`

func (q *Queries) LockFinding(ctx context.Context, findingID string) (RecoveryFinding, error) {
	row := q.db.QueryRow(ctx, lockFinding, findingID)
	var i RecoveryFinding
	err := row.Scan(
		&i.FindingID,
		&i.RunID,
		&i.Class,
		&i.ObligationID,
		&i.TenantID,
		&i.InventoryKey,
		&i.InventoryVersion,
		&i.RecordedAt,
		&i.Status,
		&i.Outcome,
		&i.EvidenceRef,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRecoveryRun = `-- name: LockRecoveryRun :one
SELECT run_id, scope_key, tenant_id, command_id, actor_id, request_digest, recovery_epoch, phase, window_start, window_end, skew_micros, reason, fenced_count, created_at, updated_at, reopened_at FROM recovery_runs WHERE run_id = $1 FOR UPDATE
`

func (q *Queries) LockRecoveryRun(ctx context.Context, runID string) (RecoveryRun, error) {
	row := q.db.QueryRow(ctx, lockRecoveryRun, runID)
	var i RecoveryRun
	err := row.Scan(
		&i.RunID,
		&i.ScopeKey,
		&i.TenantID,
		&i.CommandID,
		&i.ActorID,
		&i.RequestDigest,
		&i.RecoveryEpoch,
		&i.Phase,
		&i.WindowStart,
		&i.WindowEnd,
		&i.SkewMicros,
		&i.Reason,
		&i.FencedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReopenedAt,
	)
	return i, err
}

const maxRecoveryEpoch = `-- name: MaxRecoveryEpoch :one
SELECT coalesce(max(recovery_epoch), 0)::bigint FROM recovery_runs
`

func (q *Queries) MaxRecoveryEpoch(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxRecoveryEpoch)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reopenAdmission = `-- name: ReopenAdmission :exec
UPDATE admission_closures SET reopened_at = $3 WHERE scope_key = $1 AND run_id = $2 AND reopened_at IS NULL
`

type ReopenAdmissionParams struct {
	ScopeKey   string
	RunID      string
	ReopenedAt pgtype.Timestamptz
}

func (q *Queries) ReopenAdmission(ctx context.Context, arg ReopenAdmissionParams) error {
	_, err := q.db.Exec(ctx, reopenAdmission, arg.ScopeKey, arg.RunID, arg.ReopenedAt)
	return err
}

const updateFinding = `-- name: UpdateFinding :exec
UPDATE recovery_findings SET status = $2, outcome = $3, evidence_ref = $4, detail = $5, updated_at = $6 WHERE finding_id = $1
`

type UpdateFindingParams struct {
	FindingID   string
	Status      string
	Outcome     string
	EvidenceRef string
	Detail      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateFinding(ctx context.Context, arg UpdateFindingParams) error {
	_, err := q.db.Exec(ctx, updateFinding,
		arg.FindingID,
		arg.Status,
		arg.Outcome,
		arg.EvidenceRef,
		arg.Detail,
		arg.UpdatedAt,
	)
	return err
}

const updateRecoveryRun = `-- name: UpdateRecoveryRun :exec
UPDATE recovery_runs SET phase = $2, fenced_count = $3, updated_at = $4, reopened_at = $5 WHERE run_id = $1
`

type UpdateRecoveryRunParams struct {
	RunID       string
	Phase       string
	FencedCount int64
	UpdatedAt   pgtype.Timestamptz
	ReopenedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateRecoveryRun(ctx context.Context, arg UpdateRecoveryRunParams) error {
	_, err := q.db.Exec(ctx, updateRecoveryRun,
		arg.RunID,
		arg.Phase,
		arg.FencedCount,
		arg.UpdatedAt,
		arg.ReopenedAt,
	)
	return err
}

const upsertAdmissionClosure = `-- name: UpsertAdmissionClosure :exec
INSERT INTO admission_closures (scope_key, run_id, closed_at, reopened_at) VALUES ($1, $2, $3, NULL)
ON CONFLICT (scope_key) DO UPDATE SET run_id = EXCLUDED.run_id, closed_at = EXCLUDED.closed_at, reopened_at = NULL
`

type UpsertAdmissionClosureParams struct {
	ScopeKey string
	RunID    string
	ClosedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAdmissionClosure(ctx context.Context, arg UpsertAdmissionClosureParams) error {
	_, err := q.db.Exec(ctx, upsertAdmissionClosure, arg.ScopeKey, arg.RunID, arg.ClosedAt)
	return err
}

const upsertRecoveryProgress = `-- name: UpsertRecoveryProgress :exec
INSERT INTO recovery_progress (run_id, class, cursor, complete, seen) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, class) DO UPDATE SET cursor = EXCLUDED.cursor, complete = EXCLUDED.complete, seen = EXCLUDED.seen
`

type UpsertRecoveryProgressParams struct {
	RunID    string
	Class    string
	Cursor   string
	Complete bool
	Seen     int64
}

func (q *Queries) UpsertRecoveryProgress(ctx context.Context, arg UpsertRecoveryProgressParams) error {
	_, err := q.db.Exec(ctx, upsertRecoveryProgress,
		arg.RunID,
		arg.Class,
		arg.Cursor,
		arg.Complete,
		arg.Seen,
	)
	return err
}
