// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: releases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLineageIdentity = `-- name: GetLineageIdentity :one
SELECT tenant_id, lineage, component_id, puck_type, package_name, operation_id, brief_id, recorded_at FROM lineage_identities WHERE tenant_id = $1 AND lineage = $2
`

type GetLineageIdentityParams struct {
	TenantID string
	Lineage  string
}

func (q *Queries) GetLineageIdentity(ctx context.Context, arg GetLineageIdentityParams) (LineageIdentity, error) {
	row := q.db.QueryRow(ctx, getLineageIdentity, arg.TenantID, arg.Lineage)
	var i LineageIdentity
	err := row.Scan(
		&i.TenantID,
		&i.Lineage,
		&i.ComponentID,
		&i.PuckType,
		&i.PackageName,
		&i.OperationID,
		&i.BriefID,
		&i.RecordedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one

SELECT operation_id, tenant_id, lineage, source_revision, state, subject, subject_digest, release_id, review_effect_id, approval, approval_deadline, npm, browser, activation, catalog_revision, failure_code, revision, updated_at FROM releases WHERE operation_id = $1
`

// Releases (P21): the committed projection of a release operation,
// changed only under its expected revision.
func (q *Queries) GetRelease(ctx context.Context, operationID string) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease, operationID)
	var i Release
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.Lineage,
		&i.SourceRevision,
		&i.State,
		&i.Subject,
		&i.SubjectDigest,
		&i.ReleaseID,
		&i.ReviewEffectID,
		&i.Approval,
		&i.ApprovalDeadline,
		&i.Npm,
		&i.Browser,
		&i.Activation,
		&i.CatalogRevision,
		&i.FailureCode,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLineageIdentity = `-- name: InsertLineageIdentity :execrows

INSERT INTO lineage_identities (tenant_id, lineage, component_id, puck_type, package_name, operation_id, brief_id, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, lineage) DO NOTHING
`

type InsertLineageIdentityParams struct {
	TenantID    string
	Lineage     string
	ComponentID string
	PuckType    string
	PackageName string
	OperationID string
	BriefID     string
	RecordedAt  pgtype.Timestamptz
}

// Lineage identities (P0.8): the component identity allocated to a
// component source lineage, recorded once by the first candidate
// registration of a Generation on it and never changed.
func (q *Queries) InsertLineageIdentity(ctx context.Context, arg InsertLineageIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLineageIdentity,
		arg.TenantID,
		arg.Lineage,
		arg.ComponentID,
		arg.PuckType,
		arg.PackageName,
		arg.OperationID,
		arg.BriefID,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRelease = `-- name: InsertRelease :exec
INSERT INTO releases (operation_id, tenant_id, lineage, source_revision, state, subject, subject_digest, release_id, review_effect_id,
    approval, approval_deadline, npm, browser, activation, catalog_revision, failure_code, revision, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertReleaseParams struct {
	OperationID      string
	TenantID         string
	Lineage          string
	SourceRevision   string
	State            string
	Subject          []byte
	SubjectDigest    *string
	ReleaseID        *string
	ReviewEffectID   *string
	Approval         []byte
	ApprovalDeadline pgtype.Timestamptz
	Npm              []byte
	Browser          []byte
	Activation       []byte
	CatalogRevision  *string
	FailureCode      *string
	Revision         int64
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.Exec(ctx, insertRelease,
		arg.OperationID,
		arg.TenantID,
		arg.Lineage,
		arg.SourceRevision,
		arg.State,
		arg.Subject,
		arg.SubjectDigest,
		arg.ReleaseID,
		arg.ReviewEffectID,
		arg.Approval,
		arg.ApprovalDeadline,
		arg.Npm,
		arg.Browser,
		arg.Activation,
		arg.CatalogRevision,
		arg.FailureCode,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}

const lockRelease = `-- name: LockRelease :one
SELECT operation_id, tenant_id, lineage, source_revision, state, subject, subject_digest, release_id, review_effect_id, approval, approval_deadline, npm, browser, activation, catalog_revision, failure_code, revision, updated_at FROM releases WHERE operation_id = $1 FOR UPDATE
`

func (q *Queries) LockRelease(ctx context.Context, operationID string) (Release, error) {
	row := q.db.QueryRow(ctx, lockRelease, operationID)
	var i Release
	err := row.Scan(
		&i.OperationID,
		&i.TenantID,
		&i.Lineage,
		&i.SourceRevision,
		&i.State,
		&i.Subject,
		&i.SubjectDigest,
		&i.ReleaseID,
		&i.ReviewEffectID,
		&i.Approval,
		&i.ApprovalDeadline,
		&i.Npm,
		&i.Browser,
		&i.Activation,
		&i.CatalogRevision,
		&i.FailureCode,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRelease = `-- name: UpdateRelease :execrows
UPDATE releases SET state = $2, subject = $3, subject_digest = $4, release_id = $5, review_effect_id = $6, approval = $7,
    approval_deadline = $8, npm = $9, browser = $10, activation = $11, catalog_revision = $12, failure_code = $13, revision = $14, updated_at = $15
WHERE operation_id = $1 AND revision = $16
`

type UpdateReleaseParams struct {
	OperationID      string
	State            string
	Subject          []byte
	SubjectDigest    *string
	ReleaseID        *string
	ReviewEffectID   *string
	Approval         []byte
	ApprovalDeadline pgtype.Timestamptz
	Npm              []byte
	Browser          []byte
	Activation       []byte
	CatalogRevision  *string
	FailureCode      *string
	Revision         int64
	UpdatedAt        pgtype.Timestamptz
	ExpectedRevision int64
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRelease,
		arg.OperationID,
		arg.State,
		arg.Subject,
		arg.SubjectDigest,
		arg.ReleaseID,
		arg.ReviewEffectID,
		arg.Approval,
		arg.ApprovalDeadline,
		arg.Npm,
		arg.Browser,
		arg.Activation,
		arg.CatalogRevision,
		arg.FailureCode,
		arg.Revision,
		arg.UpdatedAt,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
